import { pgTable, integer, text, boolean, timestamp, real } from "drizzle-orm/pg-core"

export const blogEdits = pgTable("blog_edits", {
  id: integer("id").primaryKey(),
  title: text("title"),
  slug: text("slug"),
  contentHtml: text("content_html"),
  featuredImage: text("featured_image"),
  excerpt: text("excerpt"),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
})

export const jobAnnouncements = pgTable("job_announcements", {
  id: text("id").primaryKey(),
  title: text("title").notNull().default(""),
  subtitle: text("subtitle").notNull().default(""),
  publishedDate: text("published_date").notNull().default(""),
  offerNumber: text("offer_number").notNull().default(""),
  company: text("company").notNull().default(""),
  registryCode: text("registry_code").notNull().default(""),
  website: text("website").notNull().default(""),
  companyDescription: text("company_description").notNull().default(""),
  tasks: text("tasks").notNull().default(""),
  requirements: text("requirements").notNull().default(""),
  benefits: text("benefits").notNull().default(""),
  location: text("location").notNull().default(""),
  vacancies: integer("vacancies").notNull().default(1),
  salary: real("salary").notNull().default(0),
  salaryUnit: text("salary_unit").notNull().default("EUR"),
  salaryDetails: text("salary_details").notNull().default(""),
  workTime: text("work_time").notNull().default(""),
  workTimeDetails: text("work_time_details").notNull().default(""),
  startDate: text("start_date").notNull().default(""),
  applicationDeadline: text("application_deadline").notNull().default(""),
  contactName: text("contact_name").notNull().default(""),
  contactRole: text("contact_role").notNull().default(""),
  contactPhone: text("contact_phone").notNull().default(""),
  contactPhone2: text("contact_phone2").notNull().default(""),
  contactEmail: text("contact_email").notNull().default(""),
  active: boolean("active").notNull().default(true),
  slug: text("slug").notNull().default(""),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
})
