export interface BlogPost {
  id: number
  title: string
  slug: string
  date: string
  excerpt: string
  content: string
  image: string
  category: string
  readingTime: number
  author: string
}

export const blogPosts: BlogPost[] = [
  {
    id: 1,
    title: "Professionaalsed puhastusteenused mõjutavad ettevõtte tootlikkust",
    slug: "professionaalsed-puhastusteenused-mojutavad-ettevotte-tootlikkust",
    date: "2022-11-16",
    excerpt: "Puhtas ja korras töökeskkond mõjutab otseselt töötajate tootlikkust ja motivatsiooni. Uuringud näitavad, et korras kontor tõstab efektiivsust kuni 20%.",
    content: "",
    image: "/blog/koristusfirmaSPS.jpg",
    category: "Töökeskkond",
    readingTime: 4,
    author: "SPS Grupp",
  },
  {
    id: 2,
    title: "Ära astu ämbrisse – usaldusväärse koristusfirma valimine!",
    slug: "ara-astu-ambrisse-usaldusvaarse-koristusfirma-valimine",
    date: "2022-10-05",
    excerpt: "Koristusfirma valimine võib olla keeruline. Mida jälgida, et leida usaldusväärne partner? Jagame näpunäiteid koristusteenuse valikuks.",
    content: "",
    image: "/blog/koristusfirmaSPS.jpg",
    category: "Koristusteenus",
    readingTime: 5,
    author: "SPS Grupp",
  },
  {
    id: 3,
    title: "Puhastusteenused teevad tuju rõõmsaks",
    slug: "puhastusteenused-teevad-tuju-roomsaks",
    date: "2022-09-09",
    excerpt: "Korras kodune või kontorikeskkond mõjub hästi nii vaimsele tervisele kui ka üldisele heaolule. Professionaalne puhastus tagab puhtuse ja mugavuse.",
    content: "",
    image: "/blog/puhastusteenused-top.jpg",
    category: "Kodumajapidamine",
    readingTime: 3,
    author: "SPS Grupp",
  },
  {
    id: 4,
    title: "Koristusteenused Tallinnas",
    slug: "koristusteenused-tallinnas",
    date: "2022-05-20",
    excerpt: "Kvaliteetsed koristusteenused Tallinnas ja Harjumaal. SPS Grupp pakub professionaalseid puhastuslahendusi nii kontoritele, kauplustele kui tootmishoonetele.",
    content: "",
    image: "/blog/Koristamine.jpeg",
    category: "Koristusteenus",
    readingTime: 3,
    author: "SPS Grupp",
  },
  {
    id: 5,
    title: "Mis on koristusteenuse proovitöö ja vastutuskindlustus?",
    slug: "mis-on-koristusteenuse-proovitoo-ja-vastutuskindlustus",
    date: "2022-12-04",
    excerpt: "Proovitöö ja vastutuskindlustus on olulised aspektid koristusteenuse tellimisel. Selgitame, mida need tähendavad ja miks need on tähtsad.",
    content: "",
    image: "/blog/Koristamine.jpeg",
    category: "Koristusteenus",
    readingTime: 4,
    author: "SPS Grupp",
  },
  {
    id: 6,
    title: "Tee ruumides viirustele üks-null",
    slug: "tee-ruumides-viirustele-uks-null",
    date: "2020-11-24",
    excerpt: "Koroonaviiruse ajal on eriti oluline hoida tööruumid puhtad ja desinfitseeritud. Professionaalne puhastus aitab vältida viiruste levikut.",
    content: "",
    image: "/blog/Koristamine.jpeg",
    category: "Tervis ja ohutus",
    readingTime: 4,
    author: "SPS Grupp",
  },
  {
    id: 7,
    title: "Akende pesu: kuidas aknad särama lüüa?",
    slug: "akende-pesu-kuidas-aknad-sarama-luua",
    date: "2021-04-27",
    excerpt: "Akende pesu tagab puhtad aknad, mis loovad teie kodule esindusliku välimuse. Jagame nõuanded ja nipid, mille abil akende pesemine lihtsaks muuta.",
    content: "",
    image: "/blog/Koristamine.jpeg",
    category: "Kodumajapidamine",
    readingTime: 5,
    author: "SPS Grupp",
  },
  {
    id: 8,
    title: "Kontori puhastamine ja selle olulisus",
    slug: "kontori-puhastamine-ja-selle-olulisus",
    date: "2021-04-27",
    excerpt: "Miks on kontori puhastamine oluline ning mida täpsemalt sisaldab kontorite koristusteenus? Professionaalne kontoripuhastus tagab tervisliku töökeskkonna.",
    content: "",
    image: "/blog/Kontori-hoolduskoristus.jpeg",
    category: "Kontor",
    readingTime: 4,
    author: "SPS Grupp",
  },
  {
    id: 9,
    title: "Kuidas teha põranda hooldus hindele 5+?",
    slug: "kuidas-teha-poranda-hooldus-hindele-5",
    date: "2021-06-14",
    excerpt: "Põranda hooldus hoiab põranda ilusa ja kauakestvana. Loe lähemalt, kuidas erinevad puitpõranda, betoonpõranda, parketi, PVC ja linoleumi hooldus.",
    content: "",
    image: "/blog/Koristamine.jpeg",
    category: "Puhastusteenused",
    readingTime: 6,
    author: "SPS Grupp",
  },
  {
    id: 10,
    title: "Miks teha kodus suurpuhastus?",
    slug: "miks-teha-kodus-suurpuhastus",
    date: "2021-06-14",
    excerpt: "Iga kodu vajab aeg-ajalt suurpuhastust. Loe meie blogist lähemalt, kuidas see töö võimalikult meeldivalt ja efektiivselt mööda saata.",
    content: "",
    image: "/blog/Koristamine.jpeg",
    category: "Kodumajapidamine",
    readingTime: 4,
    author: "SPS Grupp",
  },
  {
    id: 11,
    title: "Vaipade puhastus ettevõttes",
    slug: "vaipade-puhastus-ettevottes",
    date: "2021-07-29",
    excerpt: "Mida vaipade puhastamisel meeles pidada, millised puhastusvahendid sobivad erinevatele plekkidele ning mida sisaldab vaipade keemilise puhastuse teenus.",
    content: "",
    image: "/blog/Koristamine.jpeg",
    category: "Puhastusteenused",
    readingTime: 5,
    author: "SPS Grupp",
  },
  {
    id: 12,
    title: "Koristusteenus tuleb appi",
    slug: "koristusteenus-tuleb-appi",
    date: "2021-07-29",
    excerpt: "Millised on erinevad koristusteenused ja millele mõelda enne koristustööde tellimist. Professionaalne koristus säästab aega ja tagab kvaliteedi.",
    content: "",
    image: "/blog/Koristamine.jpeg",
    category: "Koristusteenus",
    readingTime: 4,
    author: "SPS Grupp",
  },
  {
    id: 13,
    title: "Kontori hoolduskoristus",
    slug: "kontori-hoolduskoristus",
    date: "2021-07-29",
    excerpt: "Kas palgata oma koristaja või kasutada mõne puhastusettevõtte hoolduskoristusteenust? Võrdleme erinevaid võimalusi kontori puhtana hoidmiseks.",
    content: "",
    image: "/blog/Kontori-hoolduskoristus.jpeg",
    category: "Kontor",
    readingTime: 4,
    author: "SPS Grupp",
  },
  {
    id: 14,
    title: "Miks tellida ehitusjärgne koristus?",
    slug: "miks-tellida-ehitusjargne-koristus",
    date: "2021-08-31",
    excerpt: "Ehitusjärgne koristus tagab, et puhastatavad pinnad ja materjalid saavutavad maksimaalselt hea väljanägemise ja teenivad oma eesmärki.",
    content: "",
    image: "/blog/Koristamine.jpeg",
    category: "Puhastusteenused",
    readingTime: 4,
    author: "SPS Grupp",
  },
  {
    id: 15,
    title: "Survepesu – mitmekülgne abimees",
    slug: "survepesu-mitmekulgne-abimees",
    date: "2021-08-31",
    excerpt: "Survepesu aitab ootamatute tööde korral nagu graffiteemaldamine ning on asendamatu abimees aias olevate esemete või sõidukite puhastamisel.",
    content: "",
    image: "/blog/Koristamine.jpeg",
    category: "Välikoristus",
    readingTime: 5,
    author: "SPS Grupp",
  },
  {
    id: 16,
    title: "Keskkonnasõbralikud puhastusvahendid – miks need on olulised?",
    slug: "keskkonnasobralikud-puhastusvahendid",
    date: "2023-05-02",
    excerpt: "Keskkonnasõbralikud puhastusvahendid on ohutumad nii tervisele kui loodusele. Uuri, miks peaksid eelistama rohelisi puhastuslahendusi.",
    content: "",
    image: "/blog/Koristamine.jpeg",
    category: "Keskkond",
    readingTime: 5,
    author: "SPS Grupp",
  },
  {
    id: 17,
    title: "Soodsa hinnaga koristusteenused – kuidas hoida hinnad madalal, kuid kvaliteet kõrgel?",
    slug: "soodsa-hinnaga-koristusteenused",
    date: "2023-05-29",
    excerpt: "Kvaliteetne koristusteenus ei pea olema kallis. Avastame nipid, kuidas hoida koristusteenuse hinnad madalal ilma kvaliteeti ohverdamata.",
    content: "",
    image: "/blog/Koristamine.jpeg",
    category: "Koristusteenus",
    readingTime: 4,
    author: "SPS Grupp",
  },
  {
    id: 18,
    title: "Mis eristab koristusfirma SPS Gruppi teistest koristusettevõtetest",
    slug: "mis-eristab-sps-gruppi-teistest",
    date: "2023-06-26",
    excerpt: "SPS Grupp pakub personaalset lähenemist, sertifitseeritud kvaliteeti ja pikaajalisi partnerlussuhteid. Uuri, mis teeb meist erilise koristusfirma.",
    content: "",
    image: "/blog/Koristamine.jpeg",
    category: "Koristusteenus",
    readingTime: 3,
    author: "SPS Grupp",
  },
  {
    id: 19,
    title: "Koristaja vahetus, kas sellel on pointi?",
    slug: "koristaja-vahetus-kas-sellel-on-pointi",
    date: "2023-10-11",
    excerpt: "Koristaja vahetamine võib tuua uut värskust ja efektiivsust. Analüüsime, millal tasub kaaluda koristaja vahetust ja mida see endaga kaasa toob.",
    content: "",
    image: "/blog/Koristamine.jpeg",
    category: "Koristusteenus",
    readingTime: 4,
    author: "SPS Grupp",
  },
  {
    id: 20,
    title: "Puhastusvahendite mõju tervisele ja allergiariskid",
    slug: "puhastusvahendite-moju-tervisele-ja-allergiariskid",
    date: "2023-11-14",
    excerpt: "Puhastusvahendid võivad mõjutada meie tervist ja põhjustada allergiaid. Uuri, milliseid ohutumaid alternatiive saab kasutada igapäevases koristamises.",
    content: "",
    image: "/blog/Koristamine.jpeg",
    category: "Tervis ja ohutus",
    readingTime: 5,
    author: "SPS Grupp",
  },
  {
    id: 21,
    title: "2024 uue hooga koristusteenused",
    slug: "2024-uue-hooga-koristusteenused",
    date: "2023-12-28",
    excerpt: "Uus aasta toob uued võimalused! Millised on 2024. aasta trendid koristusteenuste vallas ja kuidas SPS Grupp saab teid aidata?",
    content: "",
    image: "/blog/Koristamine.jpeg",
    category: "Koristusteenus",
    readingTime: 3,
    author: "SPS Grupp",
  },
  {
    id: 22,
    title: "Kas prügi sorteerimine kontoris on võimalik",
    slug: "kas-prügi-sorteerimine-kontoris-on-voimalik",
    date: "2023-03-10",
    excerpt: "Prügi sorteerimine kontoris ei ole keeruline, kui selleks on loodud õige süsteem. Jagame praktilisi näpunäiteid jäätmete liigiti kogumiseks.",
    content: "",
    image: "/blog/Koristamine.jpeg",
    category: "Keskkond",
    readingTime: 4,
    author: "SPS Grupp",
  },
  {
    id: 23,
    title: "Ise koristada pole enam moes",
    slug: "ise-koristada-pole-enam-moes",
    date: "2017-10-16",
    excerpt: "Ettevõtjate seas levib järjest enam soov oma büroo- ja teeninduspindade korrashoiuks puhastusteenus sisse osta, mitte koristajaid palgal hoida.",
    content: "",
    image: "/blog/Koristamine.jpeg",
    category: "Koristusteenus",
    readingTime: 4,
    author: "Äripäev",
  },
  {
    id: 24,
    title: "Kontori koristusteenuse hind ähvardab kallineda",
    slug: "kontori-koristusteenuse-hind-ahvardab-kallineda",
    date: "2017-10-16",
    excerpt: "Miinimumpalga tõus uuel aastal kasvatab tõenäoliselt puhastusteenuste hindu, kuid kinnisvarahalduse ja tehnohoolduse hindu tööjõukulu kasv esialgu ei mõjuta.",
    content: "",
    image: "/blog/Koristamine.jpeg",
    category: "Koristusteenus",
    readingTime: 4,
    author: "Äripäev",
  },
  {
    id: 25,
    title: "Keskmisest kõrgem palk",
    slug: "keskmisest-korgem-palk",
    date: "2017-10-16",
    excerpt: "Äripäeva kinnisvarahooldajate ja -haldajate edetabeli parima, puhastusteenust pakkuva SPS Grupp OÜ juhatuse esimees Silver Bakhoff rõhutab eduka äri edendamise põhimõtteid.",
    content: "",
    image: "/blog/Koristamine.jpeg",
    category: "Koristusteenus",
    readingTime: 5,
    author: "SPS Grupp",
  },
  {
    id: 26,
    title: "Edukad kinnisvarahaldajad ja -hooldajad aastal 2016",
    slug: "edukad-kinnisvarahaldajad-ja-hooldajad-2016",
    date: "2017-10-12",
    excerpt: "SPS Grupp paistis silma edukate kinnisvarahaldajate ja -hooldajate seas. Loe lähemalt meie eduloo tagamaadest ja saavutustest.",
    content: "",
    image: "/blog/Koristamine.jpeg",
    category: "Uudised",
    readingTime: 3,
    author: "SPS Grupp",
  },
  {
    id: 27,
    title: "Edukad kinnisvara haldajad ja hooldajad aastal 2015",
    slug: "edukad-kinnisvara-haldajad-ja-hooldajad-2015",
    date: "2017-10-12",
    excerpt: "Juba 2015. aastal paistis SPS Grupp silma oma professionaalsuse ja usaldusväärsusega kinnisvarahalduse ja -hoolduse valdkonnas.",
    content: "",
    image: "/blog/Koristamine.jpeg",
    category: "Uudised",
    readingTime: 3,
    author: "SPS Grupp",
  },
  {
    id: 28,
    title: "Tipp ja Täpp koristusäris",
    slug: "tipp-ja-tapp-koristusaris",
    date: "2017-10-16",
    excerpt: "Üheksa aastat tegutsenud, mullu 50 protsendi võrra käivet ning 100 protsendi võrra kasumit kasvatanud väikeettevõtte asutasid kaks sõpra, Janar Pops ja Silver Bakhoff.",
    content: "",
    image: "/blog/Koristamine.jpeg",
    category: "Uudised",
    readingTime: 5,
    author: "Eesti Ekspress",
  },
  {
    id: 29,
    title: "Hooldus- ja haldusfirmade TOP: võitlus palga- ja hinnasurvega",
    slug: "hooldus-ja-haldusfirmade-top",
    date: "2017-10-12",
    excerpt: "Kinnisvarahoolduse ja -halduse valdkonna TOP-edetabelid näitavad, et ettevõtted peavad võitlema palga- ja hinnasurvega, säilitades samal ajal kvaliteedi.",
    content: "",
    image: "/blog/Koristamine.jpeg",
    category: "Uudised",
    readingTime: 4,
    author: "Äripäev",
  },
  {
    id: 30,
    title: "Kinnisvarahaldajate TOP: võitis puhastusfirma SPS Grupp",
    slug: "kinnisvarahaldajate-top-voitis-sps-grupp",
    date: "2017-10-12",
    excerpt: "Kinnisvarahaldajate ja -hooldajate TOP edetabelis võitis esikoha puhastusfirma SPS Grupp. Loe lähemalt meie eduloost.",
    content: "",
    image: "/blog/Koristamine.jpeg",
    category: "Uudised",
    readingTime: 3,
    author: "SPS Grupp",
  },
  {
    id: 31,
    title: "Kõige konkurentsivõimelisem mikroettevõte 2016",
    slug: "kõige-konkurentsivoimelisem-mikroettevote-2016",
    date: "2017-10-12",
    excerpt: "SPS Grupp tunnistati kõige konkurentsivõimelisemaks mikroettevõtteks 2016. aastal. See tunnustus kinnitab meie pühendumust kvaliteedile.",
    content: "",
    image: "/blog/Koristamine.jpeg",
    category: "Uudised",
    readingTime: 3,
    author: "SPS Grupp",
  },
  {
    id: 32,
    title: "Kontor",
    slug: "kontor",
    date: "2024-02-08",
    excerpt: "SPS Grupp teeb kontori säravpuhtaks! Professionaalne kontorikoristus tagab puhta ja tervisliku töökeskkonna kogu teie ettevõttele.",
    content: "",
    image: "/blog/Kontori-hoolduskoristus.jpeg",
    category: "Kontor",
    readingTime: 2,
    author: "SPS Grupp",
  },
  {
    id: 33,
    title: "Kas koristusfirma tõstab hinda?",
    slug: "kas-koristusfirma-tostab-hinda",
    date: "2024-02-08",
    excerpt: "Kas koristusfirma tõstab hinda? Enne kui lepid, küsi meilt pakkumist! Pakume konkurentsivõimelisi hindu ja kvaliteetset teenust.",
    content: "",
    image: "/blog/Koristamine.jpeg",
    category: "Koristusteenus",
    readingTime: 3,
    author: "SPS Grupp",
  },
]

export const categories = [...new Set(blogPosts.map((p) => p.category))].sort()

export function getPostsByCategory(category: string): BlogPost[] {
  return blogPosts.filter((p) => p.category === category)
}

export function getRelatedPosts(post: BlogPost, count = 3): BlogPost[] {
  return blogPosts
    .filter((p) => p.id !== post.id && p.category === post.category)
    .slice(0, count)
}

export function getPostBySlug(slug: string): BlogPost | undefined {
  return blogPosts.find((p) => p.slug === slug)
}
