import type { ServiceSeoData, SeoIcon } from "./ServiceSeoTemplate";
import { serviceSeoPages } from "./services";

const BASE_URL = "https://spsgrupp.ee";

type ExtraServiceConfig = {
  key: string;
  slug: string;
  category: "Puhastusteenused" | "Remonditeenused";
  categoryHref: string;
  serviceName: string;
  serviceType: string;
  title: string;
  accent: string;
  heroImage: string;
  contentImage: string;
  description: string;
  cta: string;
  introTitle: string;
  introFirst: string;
  introSecond: string;
  serviceTitle: string;
  groups: [string, string, string[]][];
  strengths: [string, string, SeoIcon][];
  processSteps: [string, string][];
  pricingFactors: string[];
  faqItems: { q: string; a: string }[];
  related: string[];
  icon: SeoIcon;
};

const puhastusIntro = {
  firstText: "SPS vaatab enne tööde algust pinna materjali, mustuse tüüpi, ligipääsu ja kasutuskoormust. Nii ei jää pakkumine üldiseks hinnaks, vaid muutub tööplaaniks, mille järgi saab kvaliteeti hiljem kontrollida.",
  secondText: "Tööde juures on kirjas ettevalmistus, kasutatavad meetodid, ohutus ja järelkontroll. See aitab vältida olukorda, kus eripuhastus tehakse kiiresti, aga tulemus ei kesta.",
};

const remontIntro = {
  firstText: "SPS hindab enne tööde algust ruumi kasutust, tehnilist seisukorda, ajakava ja seda, kuidas töö mõjutab hoone igapäevast toimimist.",
  secondText: "Tööplaanis on kirjas etapid, vastutus, materjalid, koristus ja üleandmine. Nii on tellijal selge, mida tehakse, millal tehakse ja kuidas tulemus vastu võetakse.",
};

function makeData(config: ExtraServiceConfig): ServiceSeoData {
  const isRemont = config.category === "Remonditeenused";
  const intro = isRemont ? remontIntro : puhastusIntro;

  return {
    slug: config.slug,
    serviceName: config.serviceName,
    serviceType: config.serviceType,
    pageUrl: `${BASE_URL}/${config.slug}`,
    category: {
      title: config.category,
      href: config.categoryHref,
    },
    metadata: {
      title: `${config.serviceName} | SPS Grupp`,
      description: config.description,
    },
    hero: {
      aria: config.serviceName,
      image: config.heroImage,
      title: config.title,
      accent: config.accent,
      description: config.description,
      cta: config.cta,
      chips: [
        { value: "SPS", label: "tööplaan", tone: "blue", icon: "clipboard" },
        { value: isRemont ? "Garantii" : "Tehnika", label: isRemont ? "töödele" : "ja vahendid", tone: "green", icon: "shield" },
        { value: "Objektijuht", label: "kontroll", tone: "navy", icon: "briefcase" },
      ],
    },
    intro: {
      title: config.introTitle,
      firstBold: config.introFirst,
      firstText: intro.firstText,
      secondBold: config.introSecond,
      secondText: intro.secondText,
    },
    strengthsIntro: isRemont
      ? "SPS Grupi remonditööde tugevus on praktiline projektijuhtimine: üks kontakt, selge ajakava, äripinna kasutusega arvestamine ja tööde korrektne üleandmine."
      : "SPS Grupi puhastusteenuste tugevus on õige meetodi valik, väljaõppega inimesed, sobiv tehnika ja objektijuhi kontroll. Eripuhastus ei ole juhuslik lisatöö, vaid planeeritud osa kinnistu korrashoiust.",
    strengths: config.strengths.map(([title, text, icon]) => ({ title, text, icon })),
    serviceContent: {
      title: config.serviceTitle,
      intro: [
        `${config.serviceName} pannakse SPSis kokku objekti tegeliku vajaduse järgi. Arvestame materjali, kasutuskoormust, tööde ajastust ja seda, kuidas teenus mõjutab hoone kasutajaid.`,
        "Hea teenuseleht peab aitama tellijal pakkumisi võrrelda. Seetõttu on siin eraldi lahti kirjutatud tööde sisu, protsess, hinnategurid ja küsimused, mida teenusepakkujalt enne otsust küsida.",
      ],
      image: config.contentImage,
      imageAlt: `SPS Grupp ${config.serviceName.toLowerCase()}`,
      imageCaption: "Täpne tööplaan sõltub objektist, materjalidest, ligipääsust ja kasutuskoormusest.",
      groups: config.groups.map(([title, kicker, items]) => ({ title, kicker, items })),
    },
    process: {
      title: `Kuidas SPS ${config.serviceName.toLowerCase()} teenust korraldab?`,
      intro: "Selge protsess teeb teenuse tellimise lihtsamaks ja annab mõlemale poolele ühise arusaama kvaliteedist, ajakavast ja vastutusest.",
      steps: config.processSteps,
    },
    buyerGuide: {
      title: `Kuidas valida ${config.serviceName.toLowerCase()} teenusepakkujat?`,
      intro: "Kõige odavam pakkumine ei pruugi olla võrreldav, kui tööde ulatus, ettevalmistus ja vastutus ei ole ühtemoodi kirjas.",
      body: "SPS soovitab võrrelda mitte ainult hinda, vaid ka tööplaani, kogemust, kasutatavaid meetodeid, objektijuhi rolli ja seda, kuidas töö vastu võetakse. Nii saab otsus põhineda sisul, mitte ainult ühel numbril.",
      goodTitle: "Mida küsida?",
      warningTitle: "Ohumärgid",
      questions: [
        "Kas pakkumine kirjeldab tööde ulatust ja sagedust?",
        "Kas objekt vaadatakse enne hinna kinnitamist üle?",
        "Kes vastutab kvaliteedikontrolli ja suhtluse eest?",
        "Pakkumine on väga üldine ja ei kirjelda töömeetodit.",
        "Ei ole selge, mis kuulub hinna sisse ja mis on lisatöö.",
        "Puudub jutt tööde üleandmisest või järelkontrollist.",
      ],
    },
    pricing: {
      title: `Millest sõltub ${config.serviceName.toLowerCase()} hind?`,
      intro: "Hind sõltub objektist ja tööde ulatusest. Täpne pakkumine vajab rohkem infot kui ainult ruutmeetrid või teenuse nimi.",
      cards: [],
      factors: config.pricingFactors,
    },
    relatedServices: [],
    faqItems: config.faqItems,
    footerCta: {
      title: `Küsige ${config.serviceName.toLowerCase()} pakkumist`,
      description: "Kirjeldage objekti ja soovitud tööde ulatust. SPS koostab tööplaani ja hinnapakkumise, mida on lihtne võrrelda.",
    },
  };
}

const extraServiceConfigs: ExtraServiceConfig[] = [
  {
    key: "puhastusteenused",
    slug: "puhastusteenused",
    category: "Puhastusteenused",
    categoryHref: "/puhastusteenused",
    serviceName: "Puhastusteenused",
    serviceType: "Eripuhastusteenused",
    title: "Puhastusteenused",
    accent: "äripindadele",
    heroImage: "/puhastusteenused1.jpg",
    contentImage: "/puhastusteenused2.jpg",
    description: "SPS Grupi eripuhastusteenused äripindadele, büroodele, tootmisruumidele ja avalikele hoonetele Tallinnas ja Harjumaal.",
    cta: "Küsi puhastusteenuse pakkumist",
    introTitle: "Eripuhastus peab lahendama konkreetse probleemi",
    introFirst: "Kui tavakoristus ei anna enam piisavat tulemust, on vaja õiget meetodit.",
    introSecond: "SPS ühendab eripuhastuse, tööplaani ja kvaliteedikontrolli.",
    serviceTitle: "Milliseid puhastusteenuseid SPS pakub?",
    groups: [
      ["Pinnad ja materjalid", "Teenused, mis taastavad pinna välimuse ja pikendavad kasutusiga.", ["Vaipade süvapuhastus", "Põrandate masinpesu ja vahatamine", "Akende ja klaaspindade pesu", "Eskalaatorite süvapuhastus"]],
      ["Objekti erivajadused", "Tööd, mis vajavad ettevalmistust, tehnikat või erimeetodit.", ["Ehitusjärgne koristus", "Suitsu- ja tulekahjustuste puhastus", "Desinfitseerimine", "Ehitusprahi äravedu"]],
      ["Töökorraldus", "SPS paneb paika, millal ja kuidas tööd tehakse.", ["Objekti ülevaatus", "Meetodi valik", "Tööde ajastamine", "Järelkontroll ja üleandmine"]],
    ],
    strengths: [["Õige meetod", "Valime töövahendid ja keemia pinna ning mustuse järgi.", "sparkle"], ["Väljaõppega tiim", "Eripuhastus nõuab kogemust, mitte ainult lisakäsi.", "users"], ["Objektijuht", "Üks vastutaja hoiab tööde ulatuse ja kvaliteedi kontrolli all.", "briefcase"], ["Turvaline teostus", "Arvestame hoone kasutajate, pindade ja tööohutusega.", "shield"]],
    processSteps: [["Objekti ülevaatus", "Täpsustame pinna, mustuse ja ligipääsu."], ["Meetodi valik", "Valime tehnika, vahendid ja tööde järjestuse."], ["Ajakava", "Planeerime töö nii, et see segaks kasutajaid võimalikult vähe."], ["Teostus", "Teeme töö kokkulepitud ulatuses."], ["Üleandmine", "Kontrollime tulemuse ja lepime vajadusel kokku hooldusrütmi."]],
    pricingFactors: ["puhastatava pinna tüüp ja seisukord", "mustuse või kahjustuse ulatus", "ligipääs ja tööde ajastus", "vajalik tehnika ja vahendid", "jäätmete kogumise või äraveo vajadus", "kas töö on ühekordne või regulaarne"],
    faqItems: [
      { q: "Kui kiiresti saate puhastusteenusega alustada?", a: "Hädaolukordades (veeavarii, tulekahju, viiruspuhang) oleme kohal 30 minuti jooksul. Plaaniliste tööde puhul alustame 1–3 tööpäeva jooksul peale kohapealset hindamist." },
      { q: "Kuidas tellida puhastusteenust Tallinnas ja Harjumaal?", a: "Helistage 662 3328 või täitke kontaktvorm. Meie spetsialist tuleb objektile, hindab vajadusi ja koostab personaalse pakkumise. Hindamine on tasuta ja kohustuseta." },
      { q: "Kas kasutate ohutuid puhastusvahendeid?", a: "Jah, kasutame ökomärgisega sertifitseeritud tooteid. Eritööde puhul valime vahendi pinna järgi, et vältida kahjustusi. Kõik vahendid vastavad EL standarditele." },
      { q: "Kas pakute tulemustele garantiid?", a: "Jah. Kui tulemus ei vasta kokkulepitud standardile, tuleme tagasi ja teeme töö ümber tasuta. Teenused on ka kindlustatud võimalike kahjude vastu." },
      { q: "Kas saate tulla ka nädalavahetusel või öösel?", a: "Jah. Paljud puhastusteenused (süvapuhastus, vaipade pesu, eskalaatorite hooldus) toimuvad õhtusel ajal või nädalavahetusel, et mitte segada teie äritegevust." },
    ],
    related: ["vaibad", "porandad", "ehitusjargne", "desinfitseerimine"],
    icon: "sparkle",
  },
  {
    key: "vaibad",
    slug: "puhastusteenused/vaipade-puhastus",
    category: "Puhastusteenused",
    categoryHref: "/puhastusteenused",
    serviceName: "Vaipade puhastus",
    serviceType: "Vaipade süvapuhastus",
    title: "Vaipade puhastus",
    accent: "äripindadel",
    heroImage: "/vaipade-puhastus-1.png",
    contentImage: "/vaipade-puhastus-2.jpg",
    description: "Vaipkatete ja kontorivaipade süvapuhastus plekkide, tolmu, allergeenide ja sissekäidud mustuse eemaldamiseks.",
    cta: "Küsi vaipade puhastuse pakkumist",
    introTitle: "Kontorivaip kogub mustust enne, kui see silma hakkab",
    introFirst: "Vaipkatte välimus mõjutab kogu ruumi muljet.",
    introSecond: "SPS valib meetodi vaiba materjali ja kasutuskoormuse järgi.",
    serviceTitle: "Mida sisaldab vaipade puhastus?",
    groups: [
      ["Ettevalmistus", "Töö algab pinna hindamisest ja sobiva meetodi valikust.", ["Vaiba materjali hindamine", "Plekkide ja käiguteede tuvastamine", "Mööbli ja ligipääsu planeerimine"]],
      ["Süvapuhastus", "Eesmärk on eemaldada mustus kiust, mitte ainult pinnalt.", ["Tolmu ja liiva eemaldus", "Ekstraktsioonpesu või muu sobiv meetod", "Plekkide lokaalne töötlus"]],
      ["Kuivamine ja üleandmine", "Tulemus peab olema kasutatav ja ruumile sobiv.", ["Kuivamisaja planeerimine", "Ventilatsiooni arvestamine", "Tulemuse kontroll"]],
    ],
    strengths: [["Materjalipõhine meetod", "Vale niiskus või keemia võib vaipa kahjustada.", "carpet"], ["Kontorite kogemus", "Planeerime töö nii, et ruum oleks kiiresti taas kasutatav.", "briefcase"], ["Plekkide käsitlus", "Eraldi tähelepanu käiguteedele ja lokatsioonidele.", "sparkle"], ["Regulaarne hooldus", "Vaip püsib kauem esinduslik, kui puhastus on planeeritud.", "clock"]],
    processSteps: [["Ülevaatus", "Hindame vaiba tüüpi ja mustuse taset."], ["Eeltöötlus", "Töötleme plekid ja käigurajad."], ["Põhipuhastus", "Teeme süvapuhastuse sobiva meetodiga."], ["Kuivamine", "Planeerime kasutuspausi."], ["Järelkontroll", "Vaatame tulemuse üle ja anname hooldussoovituse."]],
    pricingFactors: ["vaipkatte pindala", "materjal ja karva kõrgus", "plekkide ja käiguteede ulatus", "mööbli liigutamise vajadus", "tööde ajastus ja kuivamisaeg", "regulaarse hoolduse sagedus"],
    faqItems: [
      { q: "Millal on õige aeg tellida professionaalne vaipade puhastus?", a: "Tavaliselt soovitame puhastust iga kvartal või poolaasta tagant. Märgid, et aeg on käes: nähtavad plekid, ebameeldiv lõhn, vaip tundub tuhm, töötajad kaebavad sagenevate allergiate üle." },
      { q: "Kuidas minimeerida vaipade puhastuse mõju igapäevatööle?", a: "Planeerime tööd õhtuti või nädalavahetusel. Suuremas kontoris saame teha tsoonidena, et kõike korraga ei segataks. Teavitame alati eelnevalt, millal tuleme ja kui kaua kulub." },
      { q: "Milline vaibapuhastuse meetod on kõige tõhusam?", a: "Tavaliselt kasutame aurupuhastust. See eemaldab sügava mustuse ja bakterid hästi. Kõrge liiklusega kohtadele ja eriti määrdunud vaipadele keemilist süvapuhastust. Vaibatüüp määrab meetodi." },
      { q: "Kui kaua võtab vaibapuhastus aega ja kuivamine?", a: "Keskmise kontori puhastamine võtab 2–3 tundi sõltuvalt pindalast ja mööblist. Kuivpuhastusega saab kohe peale käia, aurupuhastusega kulub 6–12 tundi kuivamiseks." },
      { q: "Kas saate eemaldada vanu, sissekuivanud plekke?", a: "Enamikul juhtudel jah. Vanad plekid (kohv, vein, tint) vajavad mõnikord mitut töötluskorda. Hindame alati esmalt ja ütleme ausalt, mida on võimalik teha." },
    ],
    related: ["porandad", "kontor", "kaubandus", "ehitusjargne"],
    icon: "carpet",
  },
  {
    key: "porandad",
    slug: "puhastusteenused/porandate-hooldus",
    category: "Puhastusteenused",
    categoryHref: "/puhastusteenused",
    serviceName: "Põrandate hooldus",
    serviceType: "Põrandate masinpesu ja kaitse",
    title: "Põrandate hooldus",
    accent: "äripindadel",
    heroImage: "/porandate-hooldus-1.jpg",
    contentImage: "/porandate-hooldus-2.jpg",
    description: "Põrandate masinpesu, vahatamine, poleerimine ja kaitsekihtide uuendamine kontorites, kauplustes ja tootmishoonetes.",
    cta: "Küsi põrandate hoolduse pakkumist",
    introTitle: "Põrand kulub iga päev, isegi kui koristus toimub regulaarselt",
    introFirst: "Masinpesu ja kaitsekiht aitavad säilitada pinna välimust.",
    introSecond: "SPS seob põrandahoolduse objekti tegeliku koormusega.",
    serviceTitle: "Mida sisaldab põrandate hooldus?",
    groups: [
      ["Pinna hindamine", "Kõigepealt tuleb aru saada põranda materjalist ja seisukorrast.", ["PVC, linoleum, kivi või muu materjal", "Kulumisjälgede hindamine", "Olemasoleva kaitsekihi seis"]],
      ["Hooldustööd", "Tööde ulatus sõltub pinna seisust ja soovitud tulemusest.", ["Masinpesu", "Vana kaitsekihi eemaldus", "Vahatamine või kaitsekihi uuendamine", "Poleerimine"]],
      ["Järelhooldus", "Püsiv tulemus vajab sobivat hooldusrütmi.", ["Hooldussoovitused", "Regulaarse koristuse kooskõlastus", "Perioodilise hoolduse graafik"]],
    ],
    strengths: [["Materjalitundmine", "Iga põrand ei talu sama keemiat ega sama meetodit.", "floor"], ["Masinad ja vahendid", "Professionaalne tehnika annab ühtlasema tulemuse.", "sparkle"], ["Pinna kaitse", "Kaitsekiht lihtsustab igapäevast koristust.", "shield"], ["Äripinna ajastus", "Tööd saab planeerida siis, kui pind on vähem kasutuses.", "clock"]],
    processSteps: [["Pinna kontroll", "Selgitame materjali ja kulumise."], ["Meetodi valik", "Määrame pesu, eemaldamise ja kaitse vajaduse."], ["Tööde teostus", "Teeme masinpesu ja hoolduse etappide kaupa."], ["Kuivamine", "Planeerime kasutuspausi."], ["Hooldusrütm", "Anname soovituse järgmise hoolduse kohta."]],
    pricingFactors: ["põranda pindala ja materjal", "kulumise aste", "vana kaitsekihi eemaldamise vajadus", "mööbli või inventari liigutamine", "kuivamis- ja kasutuspaus", "hoolduse sagedus"],
    faqItems: [
      { q: "Kui sageli peaksin tellima põrandate süvapuhastuse?", a: "Kaubanduspindadel soovituslik 3–4 korda aastas, kontorites 1–2 korda aastas. Spetsiifilistel tööstusruumidel isegi igakuiselt. Täpne sagedus oleneb liikluskoormusest ja põrandatüübist." },
      { q: "Millised on märgid, et põrand vajab kiiret professionaalset hooldust?", a: "Tuhm välimus, nähtavad kriimustused, raskesti eemaldatavad plekid, viimistluskihi kulumine, värvitooni muutused, plaatide liikumine või vuukide lagunemine." },
      { q: "Kas saate hooldada kõiki põrandatüüpe?", a: "Jah — PVC, vinüül, parkett, laminaat, betoon, looduslik kivi, marmor, keraamika, epoksü. Iga tüüp nõuab erinevaid vahendeid ja tehnikat." },
      { q: "Kas süvapuhastus kahjustab põrandat?", a: "Mitte kui seda teeb professionaalne meeskond. Kahjustusi tekitab vale meetod või vahend. Meie hindame esmalt pinda ja valime ohutu lahenduse." },
      { q: "Kuidas talv mõjutab põrandaid?", a: "Talvised soolajäägid on põrandate suurim vaenlane. Sool toimib nagu liivapaber ja võib kahjustada ka kvaliteetseid põrandaid. Talvel soovitame sagedamat süvapuhastust ja porimatte sissepääsu juurde." },
    ],
    related: ["vaibad", "kaubandus", "tootmishooned", "ehitusjargne"],
    icon: "floor",
  },
  {
    key: "ehitusprahi",
    slug: "ehitusprahi-aravedu",
    category: "Puhastusteenused",
    categoryHref: "/puhastusteenused",
    serviceName: "Ehitusprahi äravedu",
    serviceType: "Ehitusprahi äravedu",
    title: "Ehitusprahi äravedu",
    accent: "Tallinnas",
    heroImage: "/ehitusprahi-aravedu-1.jpg",
    contentImage: "/ehitusprahi-aravedu-2.jpg",
    description: "Ehitusprahi, remondijäätmete ja koristusjärgse prügi äravedu korteritest, büroodest, kauplustest ja ehitusobjektidelt.",
    cta: "Küsi äraveo pakkumist",
    introTitle: "Ehituspraht ei tohi jääda tööde lõppu pidurdama",
    introFirst: "Korraldatud äravedu teeb objekti kiiremini kasutusvalmis.",
    introSecond: "SPS seob vajadusel äraveo koristuse ja remonditöödega.",
    serviceTitle: "Mida sisaldab ehitusprahi äravedu?",
    groups: [
      ["Jäätmete hindamine", "Selgitame jäätmete tüübi ja koguse.", ["Remondijäätmed", "Pakendid ja ehitusmaterjalide jäägid", "Mööbli ja inventari jäägid"]],
      ["Kandmine ja transport", "Töö korraldatakse vastavalt objektile ja ligipääsule.", ["Käsitsi kandmine", "Korruste ja lifti arvestus", "Transport jäätmejaama"]],
      ["Objekti korrastus", "Äravedu võib olla osa laiemast üleandmisest.", ["Järelkoristus", "Ehitusjärgne koristus", "Tööde ajastamine"]],
    ],
    strengths: [["Kiire korraldus", "Aitame objekti prahist vabaks saada kokkulepitud ajaks.", "clock"], ["Üks partner", "Äravedu, koristus ja vajadusel remonditööd samast kohast.", "briefcase"], ["Selge maht", "Täpsustame koguse ja ligipääsu enne pakkumist.", "clipboard"], ["Korrektne käitlus", "Jäätmed viiakse sobivasse käitluskohta.", "shield"]],
    processSteps: [["Info kogumine", "Täpsustame jäätmete tüübi, koguse ja asukoha."], ["Ligipääsu hindamine", "Arvestame korruseid, lifti, parkimist ja kandmisteed."], ["Pakkumine", "Kirjeldame tööde ulatuse ja hinna."], ["Äravedu", "Korraldame kandmise ja transpordi."], ["Järelkorrastus", "Vajadusel teeme koristuse pärast äravedu."]],
    pricingFactors: ["prahi kogus ja liik", "korrus, lift ja kandmistee", "parkimise ja ligipääsu võimalus", "jäätmete sorteerimise vajadus", "transpordi maht", "kas lisandub koristus"],
    faqItems: [
      { q: "Kui sageli peaks ehitusplatsilt prahti ära vedama?", a: "Sõltub projekti suurusest — tavaliselt 1–3 korda nädalas. Suurematel objektidel sageli igapäevaselt. Koostame graafiku vastavalt teie projekti intensiivsusele ja mahtudele." },
      { q: "Millised on ehitusprahi sorteerimise miinimumnõuded?", a: "Eesti seadusandluse kohaselt tuleb ehitusplatsil eraldada: ohtlikud jäätmed, puidujäätmed, metallijäätmed, mineraalsed jäätmed (betoon, tellised), klaas, paber ja kartong, plastid ning segaehitusjäätmed. Sorteerimata jäätmete äravedu on märkimisväärselt kallim." },
      { q: "Kui kiiresti saate konteinerit tarnida?", a: "Tavaliselt 24 tunni jooksul peale tellimust. Kiireloomuliste projektide puhul ka samal päeval. Pakume erinevaid konteinerisuurusi alates 5m³." },
      { q: "Kas tegelete ohtlike jäätmetega?", a: "Jah, oleme sertifitseeritud ohtlike jäätmete (värvid, lahustid, asbesti sisaldavad materjalid) käitlemiseks. Kogu protsess on dokumenteeritud vastavalt seadusele." },
      { q: "Kas saan tellida ka ühekordset äravedu?", a: "Jah, pakume nii regulaarseid graafikuid kui ka ühekordseid äravedusid. Eriti sobib ühekordne teenus väiksematele renoveerimisprojektidele või kiirete lõpetamiste jaoks." },
    ],
    related: ["ehitusjargne", "siseviimistlus", "lammutus", "puhastusteenused"],
    icon: "construction",
  },
  {
    key: "ehitusjargne",
    slug: "puhastusteenused/ehitusjargne-koristus",
    category: "Puhastusteenused",
    categoryHref: "/puhastusteenused",
    serviceName: "Ehitusjärgne koristus",
    serviceType: "Ehitusjärgne koristus",
    title: "Ehitusjärgne koristus",
    accent: "üleandmiseks",
    heroImage: "/ehitusjargne-koristus-1.jpg",
    contentImage: "/ehitusjargne-koristus-2.jpg",
    description: "Ehitus- ja remondijärgne põhjalik koristus tolmu, jääkide, kleebiste ja ehitusmustuse eemaldamiseks enne objekti üleandmist.",
    cta: "Küsi ehitusjärgse koristuse pakkumist",
    introTitle: "Ehitusjärgne tolm jõuab igale pinnale",
    introFirst: "Tavaline koristus ei ole pärast remonti piisav.",
    introSecond: "SPS teeb objekti üleandmiseks puhtaks süsteemselt.",
    serviceTitle: "Mida sisaldab ehitusjärgne koristus?",
    groups: [["Tolmu eemaldus", "Peen ehitustolm vajab põhjalikku lähenemist.", ["Kõrged ja madalad pinnad", "Ventilatsiooniümbrused", "Uksed, liistud ja lülitid"]], ["Pindade puhastus", "Eesmärk on üleandmiskõlblik ruum.", ["Põrandad", "Klaaspinnad ja raamid", "Sanitaarruumid ja köögialad"]], ["Lõppviimistlus", "Detailid määravad, kas ruum tundub valmis.", ["Kleebiste eemaldus", "Jääkide eemaldus", "Üleandmise kontroll"]]],
    strengths: [["Üleandmise kogemus", "Teame, millised detailid jäävad objekti vastuvõtul silma.", "clipboard"], ["Õige tehnika", "Ehitustolm vajab sobivaid masinaid ja filtreid.", "sparkle"], ["Koostöö ehitajaga", "Tööd saab siduda remondi lõppetappidega.", "briefcase"], ["Detailne kontroll", "Koristus ei lõpe põranda pesuga.", "shield"]],
    processSteps: [["Objekti info", "Täpsustame ruumid ja remondi ulatuse."], ["Tööde jaotus", "Määrame jäme- ja lõppkoristuse vajaduse."], ["Teostus", "Puhastame pinnad süsteemselt ülevalt alla."], ["Detailid", "Eemaldame kleebised ja jäägid."], ["Üleandmine", "Kontrollime valmisolekut koos tellijaga."]],
    pricingFactors: ["pindala ja ruumide arv", "ehitustolmu ja jääkide kogus", "klaaspindade ja sanitaarruumide hulk", "kleebiste või värvijääkide eemaldus", "kas vaja on prahi äravedu", "tähtaeg ja tööde ajastus"],
    faqItems: [
      { q: "Mis on ehitusjärgne koristus?", a: "Sügavpuhastus, mis eemaldab ehitusjärgse tolmu, prahi ja mustuse, tagades objekti üleandmiseks valmisoleku. Erineb tavalisest koristusest spetsiaalsete vahendite ja tehnikate poolest." },
      { q: "Kas SPS Grupp korraldab ka ehitusjäätmete äraveo?", a: "Jah, osa meie teenusest on prahi sorteerimine ja nõuetekohane äravedu sertifitseeritud käitlejatele. Kogu dokumentatsioon jäätmekaartide näol on korras." },
      { q: "Kui kiiresti saab tellida ehitusjärgse koristuse?", a: "Tavaliselt 24–48 tunni jooksul peale tellimuse kinnitamist. Kiireloomuliste projektide puhul võimalik ka samal päeval." },
      { q: "Mis maksab ehitusjärgne koristus?", a: "Teenus algab hinnast 250€, täpne pakkumine sõltub objekti suurusest, seisukorrast ja lisateenuste vajadusest. Anname alati täpse pakkumise enne töid." },
      { q: "Kas kasutate ohutuid puhastusvahendeid?", a: "Jah, kasutame ainult sertifitseeritud ja keskkonnaohutuid puhastusvahendeid. Järgime kõiki keskkonnastandardeid ja ISO 14001 nõudeid." },
    ],
    related: ["ehitusprahi", "akendePesu", "porandad", "siseviimistlus"],
    icon: "construction",
  },
  {
    key: "tulekahjustus",
    slug: "puhastusteenused/suitsu-ja-tulekahjustuste-puhastamine",
    category: "Puhastusteenused",
    categoryHref: "/puhastusteenused",
    serviceName: "Suitsu- ja tulekahjustuste puhastamine",
    serviceType: "Tulekahjustuste puhastus",
    title: "Suitsu- ja tulekahjustuste puhastamine",
    accent: "kahjustatud pindadele",
    heroImage: "/tulekahjustus1.jpg",
    contentImage: "/tulekahjustus2.jpg",
    description: "Suitsu, tahma ja põlengujärgse mustuse eemaldamine pindadelt koos tööplaani ja ohutu teostusega.",
    cta: "Küsi kahjustuste puhastuse pakkumist",
    introTitle: "Tahm ja suitsulõhn vajavad erimeetodit",
    introFirst: "Põlengujärgne puhastus ei ole tavaline suurpuhastus.",
    introSecond: "SPS hindab kahjustuse ulatust ja valib ohutu töömeetodi.",
    serviceTitle: "Mida sisaldab tulekahjustuste puhastus?",
    groups: [["Kahjustuse hindamine", "Töö algab pindade ja mustuse tüübi tuvastamisest.", ["Tahm ja suitsujäljed", "Lõhnaallikad", "Pindade tundlikkus"]], ["Puhastustööd", "Eesmärk on eemaldada mustus pinda kahjustamata.", ["Kuiv- või märgpuhastus", "Lokaalne töötlus", "Sanitaarruumide ja tehniliste pindade puhastus"]], ["Järeltegevused", "Vajadusel seotakse puhastus remondiga.", ["Lõhnade vähendamine", "Kahjustatud materjalide eemaldus", "Remonditööde planeerimine"]]],
    strengths: [["Eriolukorra kogemus", "Põlengujärgne objekt vajab rahulikku ja süsteemset tegutsemist.", "shield"], ["Õige meetod", "Tahm võib vale puhastusega sügavamale pinda minna.", "sparkle"], ["Koostöö remondiga", "SPS saab vajadusel siduda puhastuse taastamistöödega.", "briefcase"], ["Selge ulatus", "Kirjeldame, mida puhastatakse ja mis vajab remonti.", "clipboard"]],
    processSteps: [["Ülevaatus", "Hindame kahjustuse ulatust."], ["Meetodi valik", "Määrame pindadele sobiva puhastusviisi."], ["Testpuhastus", "Vajadusel kontrollime meetodit väiksel alal."], ["Põhitöö", "Puhastame kokkulepitud pinnad."], ["Soovitus", "Anname ülevaate järgmistest sammudest."]],
    pricingFactors: ["kahjustatud pinna suurus", "tahma ja suitsu ulatus", "materjalide tundlikkus", "ligipääs ja ohutus", "lõhnaeemalduse vajadus", "kas lisanduvad remonditööd"],
    faqItems: [
      { q: "Kui kiiresti tuleb alustada puhastusprotsessiga?", a: "Esimese 24-48 tunni jooksul on kriitiline kutsuda professionaalne meeskond. Iga viivitatud tund voib suurendada loplikke kulusid kuni 25% ja raskendada taastamist." },
      { q: "Kas kindlustus katab koik kulud?", a: "Professionaalne dokumentatsioon suurendab margatavalt huvitise saamise toenaosust. Teeme alati pohjaliku kahjustuste kirjelduse koos fotodega, mille saab kindlustusseltsile esitada." },
      { q: "Kui ohtlikud on tulekahjujargsed mikroosakesed?", a: "Voivad pohjustada tosiseid hingamisteede probleeme, kui neid oigeaegselt ei eemaldata. Samuti suuivad nad materjalidesse ja on hiljem vaga raskesti eemaldatavad." },
      { q: "Kas lohn jaab alles ka parast puhastust?", a: "Ei. Kasutame professionaalseid ohupuhastusseadmeid ja neutralisaatoreid, mis eemaldavad lohna molekulaarsel tasandil. Lohn ei tule tagasi." },
      { q: "Kui kaua puhastusprotsess kestab?", a: "Keskmiselt 1-3 toopaeva soltuvalt kahjustuste ulatusest ja ruumi suurusest. Suuremate juhtumite puhul voib votta nadala voi rohkem." },
    ],
    related: ["siseviimistlus", "lammutus", "ehitusprahi", "desinfitseerimine"],
    icon: "sparkle",
  },
  {
    key: "eskalaatorid",
    slug: "puhastusteenused/eskalaatorite-suvapuhastus",
    category: "Puhastusteenused",
    categoryHref: "/puhastusteenused",
    serviceName: "Eskalaatorite süvapuhastus",
    serviceType: "Eskalaatorite puhastus",
    title: "Eskalaatorite süvapuhastus",
    accent: "kaubanduspindadel",
    heroImage: "/eskalaatorite-suvapuhastus-1.jpg",
    contentImage: "/eskalaatorite-suvapuhastus-2.jpg",
    description: "Eskalaatorite astmete, soonte ja külgpindade süvapuhastus kaubanduskeskustes, büroohoonetes ja avalikes hoonetes.",
    cta: "Küsi eskalaatorite puhastuse pakkumist",
    introTitle: "Eskalaator näitab mustust eriti kiiresti",
    introFirst: "Suur kasutuskoormus kogub mustuse astmesoontesse.",
    introSecond: "SPS planeerib töö ajal, mil see ei sega külastajate liikumist.",
    serviceTitle: "Mida sisaldab eskalaatorite süvapuhastus?",
    groups: [["Ettevalmistus", "Töö vajab ohutut ajastust ja ligipääsu.", ["Tööaja kokkulepe", "Ohutuspiirangud", "Pinna seisukorra hindamine"]], ["Süvapuhastus", "Eesmärk on eemaldada mustus ka soonte seest.", ["Astmete puhastus", "Külgpindade puhastus", "Käsipuude puhastus"]], ["Kontroll", "Tulemus antakse üle kasutuskoormust arvestades.", ["Visuaalne kontroll", "Libeduse ja jääkide kontroll", "Hooldusrütmi soovitus"]]],
    strengths: [["Kaubanduspindade kogemus", "Arvestame külastajate liikumist ja tööde ajastust.", "store"], ["Detailne puhastus", "Töötame ka soonte ja raskesti ligipääsetavate kohtadega.", "sparkle"], ["Ohutu korraldus", "Tööala ja ajastus lepitakse kokku ette.", "shield"], ["Regulaarne graafik", "Suure koormusega objektidel saab teha perioodilise hoolduse.", "clock"]],
    processSteps: [["Ajakava", "Lepime kokku sobiva tööaja."], ["Ettevalmistus", "Piirame tööala ja valmistame pinnad ette."], ["Puhastus", "Puhastame astmed, sooned ja külgpinnad."], ["Kuivatus", "Jälgime, et pind jääks kasutuskõlblik."], ["Üleandmine", "Kontrollime tulemuse objektijuhiga."]],
    pricingFactors: ["eskalaatorite arv", "mustuse ja kasutuskoormuse tase", "tööde ajastus", "ligipääs ja ohutusnõuded", "kas töö on ühekordne või regulaarne", "lisapindade puhastuse vajadus"],
    faqItems: [
      { q: "Kui kaua võtab eskalaatori süvapuhastus aega?", a: "Keskmiselt 2–4 tundi seadme kohta, sõltuvalt suurusest ja määrdumisastmest. Kaubanduskeskustes, kus on mitu eskalaatorit, planeerime töö ühele ööle." },
      { q: "Kas puhastus segab äritegevust?", a: "Ei. Töötame siis, kui kaubanduskeskus on suletud — öösel või enne avamist. Hommikul on eskalaator jälle töökorras." },
      { q: "Kui sageli peaks eskalaatorit süvapuhastama?", a: "Keskmiselt 2–4 korda aastas, sõltuvalt kasutussagedusest ja asukohast. Suure liiklusega kaubanduskeskustes sagedamini." },
      { q: "Kas puhastusvahendid on ohutud seadmetele?", a: "Jah, kasutame ainult sertifitseeritud vahendeid, mis on ohutud nii mehhanismidele kui inimestele. Eskalaatorile mitte kunagi survepesu." },
      { q: "Kas regulaarne süvapuhastus aitab vähendada kulumist?", a: "Jah, selgelt. Regulaarne süvapuhastus vähendab mustusest tingitud kulumist ja pikendab eskalaatorite eluiga aastate võrra. Säästab suuri remondikulusid." },
    ],
    related: ["kaubandus", "porandad", "akendePesu", "desinfitseerimine"],
    icon: "store",
  },
  {
    key: "desinfitseerimine",
    slug: "puhastusteenused/desinfitseerimine",
    category: "Puhastusteenused",
    categoryHref: "/puhastusteenused",
    serviceName: "Desinfitseerimine",
    serviceType: "Desinfitseerimine",
    title: "Desinfitseerimine",
    accent: "äripindadel",
    heroImage: "/desinfitseerimine-1.jpg",
    contentImage: "/desinfitseerimine-2.png",
    description: "Kontaktpindade, sanitaarruumide ja tööruumide desinfitseerimine büroodes, koolides, kauplustes ja tootmishoonetes.",
    cta: "Küsi desinfitseerimise pakkumist",
    introTitle: "Desinfitseerimine peab olema sihipärane, mitte juhuslik pihustamine",
    introFirst: "Oluline on teada, milliseid pindu ja riske käsitletakse.",
    introSecond: "SPS seob desinfitseerimise koristusplaani ja kasutuskoormusega.",
    serviceTitle: "Mida sisaldab desinfitseerimine?",
    groups: [["Riskipinnad", "Töö algab kontaktpindade ja kasutuskoormuse kaardistusest.", ["Ukselingid ja lülitid", "Tööpinnad", "Sanitaarruumid", "Ühiskasutusalad"]], ["Teostus", "Vahendid valitakse pinna ja eesmärgi järgi.", ["Pindade puhastus enne desinfitseerimist", "Sobiva vahendi kasutus", "Mõjuaegade arvestamine"]], ["Korraldus", "Teenust saab siduda regulaarse koristusega.", ["Päevane lisakontroll", "Töövälisel ajal teostus", "Dokumenteeritud tööplaan"]]],
    strengths: [["Sihipärane töö", "Desinfitseerime riskipindu, mitte lihtsalt õhku.", "shield"], ["Õiged vahendid", "Kasutame pindu arvestavaid lahendusi.", "sparkle"], ["Koristusplaani osa", "Teenuse saab siduda igapäevase koristusega.", "clipboard"], ["Sobib avalikele pindadele", "Koolid, kontorid, kauplused ja tootmisruumid.", "briefcase"]],
    processSteps: [["Riskide kaardistus", "Täpsustame pinnad ja kasutuskoormuse."], ["Puhastus", "Vajadusel puhastame pinna enne desinfitseerimist."], ["Desinfitseerimine", "Kasutame kokkulepitud vahendeid ja meetodit."], ["Mõjuaeg", "Arvestame vahendi toimimiseks vajalikku aega."], ["Graafik", "Soovitame sobiva korduse vajadusel."]],
    pricingFactors: ["ruumide pindala", "kontaktpindade hulk", "sanitaarruumide arv", "tööde sagedus", "tööde ajastus", "kas teenus lisandub regulaarsele koristusele"],
    faqItems: [
      { q: "Kui tihti peaks kontoriruume professionaalselt desinfitseerima?", a: "Viiruste kõrghooajal (oktoobrist märtsini) soovitame täielikku desinfitseerimist vähemalt kord kuus, lisaks igapäevastele puutepunktide puhastustele. Madala riskiga perioodidel kvartaalne hooldus." },
      { q: "Kas desinfitseerimine kahjustab mööblit või elektroonikat?", a: "Ei, kui kasutatakse õigeid vahendeid. Professionaalne desinfitseerija valib meetodi pinna järgi. Tundliku elektroonika jaoks on eraldi lahendused. Enne teenust mainige alati eritingimusi." },
      { q: "Kui kaua võtab desinfitseerimine aega?", a: "Keskmise kontori (200–500m²) desinfitseerimine võtab 1–3 tundi sõltuvalt meetodist. Ruumid on sageli kasutatavad kohe pärast töö lõppu." },
      { q: "Millised on tõhusad puutepunktid, mida sageli puhastada?", a: "Telefonid (kuni 25 000 mikroobi/cm²), ukselingid, kohvimasina nupud, koosolekuruumide lauad ja toolid, lülitid ning käsipuud. Need on kontoris kõige suurema nakkusriskiga." },
      { q: "Kas teenus on efektiivne COVID-19 ja gripi vastu?", a: "Jah, meie kasutatavad vahendid on testitud ja tõestatud efektiivsusega nii COVID-19 kui ka gripi, noroviiruse ja teiste hingamisteede viiruste vastu." },
    ],
    related: ["koolid", "kontor", "kaubandus", "puhastusteenused"],
    icon: "shield",
  },
  {
    key: "remonditeenused",
    slug: "remonditeenused-tallinnas",
    category: "Remonditeenused",
    categoryHref: "/remonditeenused-tallinnas",
    serviceName: "Remonditeenused",
    serviceType: "Remonditeenused äripindadele",
    title: "Remonditeenused",
    accent: "Tallinnas",
    heroImage: "/remonditeenused-1.jpg",
    contentImage: "/remonditood-2.webp",
    description: "SPS Grupi remonditeenused äripindadele, büroodele, kauplustele ja kinnistutele Tallinnas ning Harjumaal.",
    cta: "Küsi remonditööde pakkumist",
    introTitle: "Äripinna remont vajab rohkemat kui üksik töömees",
    introFirst: "Ajakava, puhtus ja vastutus mõjutavad äri igapäevast toimimist.",
    introSecond: "SPS korraldab remonditööd ühe kontaktiga ja selge tööplaaniga.",
    serviceTitle: "Milliseid remonditeenuseid SPS pakub?",
    groups: [["Tehnilised tööd", "Kiired ja planeeritud tööd hoone toimimiseks.", ["Elektritööd", "Torutööd", "Ventilatsiooni ehitus ja hooldus"]], ["Sise- ja sanitaartööd", "Ruumide uuendamine kasutust arvestades.", ["Siseviimistlustööd", "Plaatimistööd", "Sanitaarremont"]], ["Kinnistu tööd", "Tööd, mis toetavad hoone terviklikku korrashoidu.", ["Katuse remont", "Lammutustööd", "Ehitusprahi äravedu"]]],
    strengths: [["Üks kontakt", "Tellijal on selge vastutaja tööde käigus.", "briefcase"], ["Äripinna loogika", "Arvestame kasutajate, töötajate ja klientide liikumisega.", "store"], ["Koristusega seotud", "Remondijärgne korrastus saab olla osa samast lahendusest.", "sparkle"], ["Dokumenteeritud üleandmine", "Tööde lõpus on selge, mis tehtud ja kuidas üle antud.", "clipboard"]],
    processSteps: [["Vajaduse kaardistus", "Täpsustame tööde ulatuse ja prioriteedid."], ["Objekti ülevaatus", "Hindame tehnilist seisu ja ligipääsu."], ["Tööplaan", "Koostame ajakava ja vastutuse."], ["Teostus", "Korraldame tööd kokkulepitud etappides."], ["Üleandmine", "Kontrollime tulemuse ja teeme vajadusel järelkoristuse."]],
    pricingFactors: ["tööde liik ja ulatus", "objekti tehniline seis", "materjalid ja tarvikud", "tööde ajastus", "ligipääs ja kasutajatega arvestamine", "kas lisandub koristus või jäätmete äravedu"],
    faqItems: [
      { q: "Kas SPS Grupp teeb kõiki remonditöid ise või kasutab alltöövõtjaid?", a: "Enamik töid (elekter, toru, viimistlus, plaatimine, lammutus) teeme ise oma sertifitseeritud meeskonnaga. Eriti spetsiifilistel töödel võime kaasata usaldusväärseid partnereid — kuid teie ees vastutame alati meie." },
      { q: "Kas saate teha remonditöid tööajal segamata?", a: "Jah. Planeerime töö nii, et teie äritegevus ei katkeks. Teeme tööd õhtuti, nädalavahetustel või tsooniti. Mürarohked tööd planeerime tööaja välisele ajale." },
      { q: "Kui kiiresti saab remonditööde pakkumist?", a: "Tavaliselt 2–5 tööpäeva pärast kohapealset ülevaatust. Väiksemate tööde puhul ka kiiremini. Kiireloomulistes olukordades reageerime samal päeval." },
      { q: "Kas annate remonditöödele garantii?", a: "Jah. Kõigile teostatud töödele kehtib garantii vastavalt kokkuleppele — tavaliselt 1–5 aastat sõltuvalt töö iseloomust. Materjalidele kehtib tootja garantii." },
      { q: "Kas tegelete ka kiireloomuliste hädaolukordadega?", a: "Jah — veeavarii, elektririke, kanalisatsiooniummistus. Reageerime 24/7, kohapeal tavaliselt 1–2 tunni jooksul." },
    ],
    related: ["elektritood", "torutood", "siseviimistlus", "sanitaar"],
    icon: "briefcase",
  },
  {
    key: "elektritood",
    slug: "remonditeenused-tallinnas/elektritood",
    category: "Remonditeenused",
    categoryHref: "/remonditeenused-tallinnas",
    serviceName: "Elektritööd",
    serviceType: "Elektritööd äripindadele",
    title: "Elektritööd",
    accent: "äripindadele",
    heroImage: "/images/elekter/ElekterHero.png",
    contentImage: "/images/elekter/Elekter1.webp",
    description: "Elektritööd, valgustuse uuendamine, rikete lahendamine ja tehniline hooldus äripindadel Tallinnas ning Harjumaal.",
    cta: "Küsi elektritööde pakkumist",
    introTitle: "Elektritööd äripinnal peavad olema ohutud ja planeeritud",
    introFirst: "Rike või kehv lahendus mõjutab kohe hoone kasutust.",
    introSecond: "SPS seob tehnilise töö ajakava, ohutuse ja üleandmisega.",
    serviceTitle: "Mida sisaldavad elektritööd?",
    groups: [["Rikked ja hooldus", "Kiired tööd hoone toimimise taastamiseks.", ["Rikete tuvastamine", "Lülitite ja pistikute vahetus", "Valgustuse hooldus"]], ["Uuendused", "Planeeritud tööd ruumi paremaks kasutamiseks.", ["Valgustuse uuendamine", "Lisapistikud", "Kaabeldustööd"]], ["Ohutus ja dokumentatsioon", "Töö peab olema kontrollitav.", ["Tööde üleandmine", "Ohutusnõuete järgimine", "Edasiste tööde soovitused"]]],
    strengths: [["Ärikinnisvara kogemus", "Tööd planeeritakse hoone kasutust arvestades.", "briefcase"], ["Ohutus", "Elektritööde puhul ei tohi vastutus jääda ebamääraseks.", "shield"], ["Kiire reageerimine", "Rikete korral on oluline taastada töökorraldus.", "clock"], ["Selge üleandmine", "Tellijal peab olema arusaam tehtud töödest.", "clipboard"]],
    processSteps: [["Probleemi kirjeldus", "Täpsustame töö vajaduse."], ["Ülevaatus", "Hindame olukorra kohapeal."], ["Pakkumine", "Kirjeldame tööde ulatuse."], ["Teostus", "Teeme töö kokkulepitud ajal."], ["Kontroll", "Anname töö üle ja selgitame tulemust."]],
    pricingFactors: ["tööde liik ja keerukus", "materjalide vajadus", "ligipääs tehnosüsteemidele", "rikke kiireloomulisus", "tööde ajastus", "vajalikud mõõtmised või kontroll"],
    faqItems: [
      { q: "Kas teete ka kodupinna elektritöid?", a: "Ei — spetsialiseerume äriklientidele. Kodupinna elektritöödeks soovitame pöörduda kodumajapidamistele spetsialiseerunud elektriku poole. Äriklientide puhul on meie kogemused, kiirus ja dokumentatsioon teistmoodi, ning see peegeldub ka hinnas." },
      { q: "Kui kiiresti reageerite elektririkkele?", a: "Harjumaa piirkonnas 2 tunni jooksul plaaniliste rikete puhul. Kriitiliste süsteemide (serveriruum, kaubandus, meditsiiniasutused) jaoks on lepinguliselt kokku leppida võimalik 30-minutiline reageering. Tööajavälisel ajal (õhtu, nädalavahetus) on hädaabireageering võimalik, hind on siis kõrgem." },
      { q: "Kas LED-üleminek tasub end ära?", a: "Enamikel juhtudel jah. Keskmine kontor säästab 40–60% valgustuskuludest ja investeering teenib end tagasi 2–4 aastaga. Nutilahendustega (liikumis-, valgusandurid) on sääst veel suurem. Täpne arvestus sõltub teie praegustest kuludest, valgustuse kasutustihedusest ja valgustite arvust. Teeme vajadusel energiaefektiivsuse arvutuse enne investeerimist." },
      { q: "Milline peab olema ärihoone elektrisüsteemi hooldusgraafik?", a: "Iga-aastane visuaalne ülevaatus ja termograafilist kontrolli kilbist. Iga 5 aasta tagant põhjalikum audit. Pistikupesade ja lülitite pistelised kontrollid. Kriitilistel süsteemidel (serveriruumid) kord poolaastas. Hoolduslepingu klientide jaoks hoolitseme kogu graafiku eest ise." },
      { q: "Kas paigaldate ka elektriautode laadimisjaamu?", a: "Jah — nii tavalaadijaid (AC 7–22 kW) kui kiirlaadijaid (DC 50 kW+). Meil on kogemus nii töötajate parklatega kui avalike laadimisjaamadega kaubanduskeskustes ja hotellides. Teeme terviklikuma paketi — taristu, paigaldus, makselahendus, kaugjälgimine." },
      { q: "Kas elektritööd nõuavad loa?", a: "Osa elektritöid nõuab elektriohutuse seaduse järgi pädevat isikut (meie elektrikud on litsentseeritud). Suurematele uusprojektidele võib vaja olla ehitusluba ja projektdokumentatsiooni — me haldame kogu protsessi kliendile nähtamatult. Pärast tööde lõppu väljastame tegevuspäeviku ja mõõtmisprotokollid, mis on vajalikud nii auditeerimise kui kindlustuse jaoks." },
      { q: "Kas saaks ainult lubatud osa süsteemist uuendada, mitte kõike korraga?", a: "Jah — see ongi meie standardlähenemine ärikinnisvarale. Uuendame etappide kaupa, nii et teie äritegevus ei seisaks seisma. Sageli teeme töid õhtuti, nädalavahetustel või tühjade ruumide kaupa. Kogu plaan on ette paigas ja te teate, millal mis etapp tuleb." },
    ],
    related: ["torutood", "ventilatsioon", "siseviimistlus", "remonditeenused"],
    icon: "shield",
  },
  {
    key: "torutood",
    slug: "remonditeenused-tallinnas/torutood",
    category: "Remonditeenused",
    categoryHref: "/remonditeenused-tallinnas",
    serviceName: "Torutööd",
    serviceType: "Torutööd äripindadele",
    title: "Torutööd",
    accent: "Tallinnas",
    heroImage: "/torutood-1.jpg",
    contentImage: "/torutood-2.webp",
    description: "Torutööd, lekete kõrvaldamine, sanitaartehnika paigaldus ja hooldus äripindadel ning kinnistutel.",
    cta: "Küsi torutööde pakkumist",
    introTitle: "Torurike vajab kiiret ja selget tegutsemist",
    introFirst: "Veeavarii või lekkiv süsteem võib tekitada suuremat kahju.",
    introSecond: "SPS korraldab torutööd koos vajadusel koristuse ja taastamisega.",
    serviceTitle: "Mida sisaldavad torutööd?",
    groups: [["Avariid ja rikked", "Kiire lahendus kahju piiramiseks.", ["Lekete tuvastamine", "Torude parandused", "Ummistuste lahendamine"]], ["Paigaldus", "Sanitaarruumide ja tehnosõlmede tööd.", ["Segistid ja valamud", "WC-potid ja loputuskastid", "Torustiku osade vahetus"]], ["Järeltegevused", "Pärast riket on oluline ruum taastada.", ["Niiskuskahju hindamine", "Koristus", "Siseviimistluse taastamine"]]],
    strengths: [["Kiire reageerimine", "Lekke puhul loeb aeg.", "clock"], ["Äripinna kogemus", "Töö tuleb teha kasutajaid arvestades.", "briefcase"], ["Täislahendus", "Torutöö, koristus ja taastamine saavad olla seotud.", "sparkle"], ["Selge vastutus", "Tellijal on üks kontakt kogu tööks.", "clipboard"]],
    processSteps: [["Probleemi kirjeldus", "Täpsustame rikke või töö ulatuse."], ["Kohapealne kontroll", "Hindame ligipääsu ja vajalikke materjale."], ["Lahendus", "Teeme paranduse või paigalduse."], ["Test", "Kontrollime toimivust."], ["Järelkorraldus", "Vajadusel planeerime koristuse või taastamise."]],
    pricingFactors: ["rikke või töö ulatus", "materjalide vajadus", "ligipääs torustikule", "kiireloomulisus", "tööde ajastus", "kas lisandub koristus või taastamine"],
    faqItems: [
      { q: "Kui kiiresti reageerite veelekke hädaolukorras?", a: "Tavaliselt 1-2 tunni jooksul Tallinnas ja Harjumaal. Öisel ajal sama - reageerime 24/7." },
      { q: "Kas teete ka uute torustike paigaldust?", a: "Jah, tegeleme nii uutel ehitustel kui ka renoveerimistel. Oskused hõlmavad vee-, kanalisatsiooni- ja küttesüsteeme kõikides tavalistes materjalides." },
      { q: "Kuidas leiate peidetud veelekke?", a: "Kasutame termokaameraid, kuulmismeetodit ja rõhu testimist. Enamikul juhtudel leiame lekke kohe ilma suuri lõhkumistöid tegemata." },
      { q: "Kas annate garantii torutöödele?", a: "Jah. Töödele 2 aastat, materjalidele tootja garantii. Kõik dokumenteeritud kirjalikult." },
      { q: "Kas tegelete ka küttesüsteemide probleemidega?", a: "Jah. Keskkütte, radiaatorite, põrandakütte ja boilerite paigaldus, hooldus ning remont. Talvel hoiame teie hoone soojas." },
    ],
    related: ["sanitaar", "siseviimistlus", "elektritood", "remonditeenused"],
    icon: "shield",
  },
  {
    key: "siseviimistlus",
    slug: "remonditeenused-tallinnas/siseviimistlustood",
    category: "Remonditeenused",
    categoryHref: "/remonditeenused-tallinnas",
    serviceName: "Siseviimistlustööd",
    serviceType: "Siseviimistlustööd äripindadel",
    title: "Siseviimistlustööd",
    accent: "äripindadel",
    heroImage: "/siseviimistlus-1.jpg",
    contentImage: "/siseviimistlus-2.webp",
    description: "Siseviimistlustööd, värvimine, pahteldus, parandused ja ruumide värskendamine büroodes ning äripindadel.",
    cta: "Küsi siseviimistluse pakkumist",
    introTitle: "Siseviimistlus peab sobima ruumi kasutusega",
    introFirst: "Äripinnal loeb lisaks välimusele ka tööde tempo ja puhtus.",
    introSecond: "SPS planeerib viimistlustööd nii, et pind saaks kiiresti kasutusse.",
    serviceTitle: "Mida sisaldavad siseviimistlustööd?",
    groups: [["Ettevalmistus", "Hea tulemus algab aluspinnast.", ["Pindade kaitsmine", "Pahteldus ja lihvimine", "Vigastuste parandamine"]], ["Viimistlus", "Tööde ulatus sõltub ruumi seisust.", ["Värvimine", "Seinte ja lagede värskendus", "Liistude ja detailide viimistlus"]], ["Üleandmine", "Äripind peab jääma kasutusvalmis.", ["Tööde kontroll", "Järelkoristus", "Puuduste nimekiri vajadusel"]]],
    strengths: [["Kiire töökorraldus", "Ajakava on äripinnal sama oluline kui värvitoon.", "clock"], ["Puhas töökoht", "Kaitseme pinnad ja seome töö järelkoristusega.", "sparkle"], ["Projektijuhtimine", "Üks kontakt hoiab tööde järjekorra kontrolli all.", "briefcase"], ["Kvaliteetne lõpptulemus", "Detailid otsustavad, kas ruum näeb professionaalne välja.", "shield"]],
    processSteps: [["Ülevaatus", "Hindame pindade seisukorda."], ["Tööplaan", "Lepime kokku materjalid ja etapid."], ["Ettevalmistus", "Kaitseme pinnad ja parandame aluspinnad."], ["Viimistlus", "Teostame kokkulepitud tööd."], ["Üleandmine", "Kontrollime tulemuse ja koristame tööala."]],
    pricingFactors: ["ruumide pindala", "pindade seisukord", "pahtelduse ja paranduste maht", "materjalide valik", "tööde ajastus", "kas lisandub koristus või prahi äravedu"],
    faqItems: [
      { q: "Kui kaua võtab kontori seinte värvimine aega?", a: "Väikse kontori (50-100 m²) värvimine võtab tavaliselt 2-3 tööpäeva: pahteldus, krunt ja 2 kihti värvi. Suurema pinna puhul proportsionaalselt kauem. Tähtaeg sõltub ka kuivamise ajast." },
      { q: "Kas saate teha tööd öösel või nädalavahetusel?", a: "Jah, kui teie äritegevus nõuab seda. Öised ja nädalavahetuse tööd võivad olla pisut kallimad, aga väldivad katkestusi teie töös." },
      { q: "Milliseid materjale kasutate?", a: "Kasutame professionaalseid vesilahustuvaid värve nagu Tikkurila, Sadolin ja Caparol, samuti kvaliteetseid pahtleid ja krunte. Kliendi soovi järgi kasutame ka ökomärgisega tooteid." },
      { q: "Kas värvimise ajal saab kontoris töötada?", a: "Osaliselt jah. Saame töötada tsooni kaupa ning kaitseme tehnikat ja mööblit. Vesilahustuvad värvid ei eralda tugevaid ebameeldivaid lõhnu. Suuremate värvimistööde puhul on siiski efektiivsem planeerida ruum mõneks ajaks tühjaks." },
      { q: "Kas annate garantii?", a: "Jah. Siseviimistlustöödele anname 2 aastat garantiid. Materjalidele kehtib tootja garantii." },
    ],
    related: ["plaatimine", "sanitaar", "ehitusprahi", "ehitusjargne"],
    icon: "briefcase",
  },
  {
    key: "sanitaar",
    slug: "remonditeenused-tallinnas/sanitaarremont-ja-umberehitus",
    category: "Remonditeenused",
    categoryHref: "/remonditeenused-tallinnas",
    serviceName: "Sanitaarremont",
    serviceType: "Sanitaarremont ja ümberehitus",
    title: "Sanitaarremont",
    accent: "äripindadel",
    heroImage: "/sanitaarremont-1.jpg",
    contentImage: "/sanitaarremont-2.webp",
    description: "Sanitaarruumide remont, ümberehitus, plaatimine, torutööd ja viimistlus äripindadel ning ühiskasutatavates hoonetes.",
    cta: "Küsi sanitaarremondi pakkumist",
    introTitle: "Sanitaarruum peab taluma igapäevast koormust",
    introFirst: "Vale lahendus kulub kiiresti ja tekitab lisakulusid.",
    introSecond: "SPS ühendab toru-, plaatimis- ja viimistlustööd üheks tööplaaniks.",
    serviceTitle: "Mida sisaldab sanitaarremont?",
    groups: [["Planeerimine", "Sanitaarruumi remont vajab tehnilist läbimõtlemist.", ["Vajaduse kaardistus", "Materjalide valik", "Tööde etappide planeerimine"]], ["Tehnilised tööd", "Aluspind ja veekindlus määravad kestvuse.", ["Torutööd", "Hüdroisolatsioon", "Plaatimine"]], ["Viimistlus", "Ruum peab jääma kasutajale mugav ja vastupidav.", ["Sanitaartehnika paigaldus", "Värvimine ja liistud", "Järelkoristus"]]],
    strengths: [["Täislahendus", "Torutöö, plaatimine ja viimistlus ühe korraldusega.", "briefcase"], ["Niiskuskindlus", "Hüdroisolatsioon ja materjalid peavad sobima koormusega.", "shield"], ["Ajakava", "Ühiskasutatav ruum peab kiiresti tagasi kasutusse jõudma.", "clock"], ["Koristus kaasas", "Üleandmine sisaldab vajadusel remondijärgset koristust.", "sparkle"]],
    processSteps: [["Ülevaatus", "Hindame ruumi seisukorda ja tehnilist vajadust."], ["Tööplaan", "Koostame etapid ja materjalid."], ["Lammutus ja ettevalmistus", "Eemaldame vana lahenduse vajadusel."], ["Remont", "Teeme tehnilised ja viimistlustööd."], ["Üleandmine", "Kontrollime toimivust ja puhtust."]],
    pricingFactors: ["ruumi suurus", "torutööde maht", "plaatimise ja hüdroisolatsiooni vajadus", "sanitaartehnika valik", "lammutuse ja prahi äraveo maht", "tööde ajastus"],
    faqItems: [
      { q: "Kui kaua võtab sanitaarruumi täielik remont?", a: "Väike WC-ruum tavaliselt 1-2 nädalat, keskmine 2-3 nädalat, suurem 3-5 nädalat. Täpne aeg sõltub töö mahust ja materjalide saabumisest." },
      { q: "Kas saate teha osalist remonti, näiteks ainult plaatimist?", a: "Jah, saame teha osalisi töid. Samas võib täielik remont olla sageli kulutõhusam, sest paljud tööd on omavahel seotud." },
      { q: "Kas tegelete ka jäätmete äraveoga?", a: "Jah, lammutusjäätmete sorteerimine ja nõuetekohane äravedu on meie teenuses sees." },
      { q: "Kas saate pakkuda ka sanitaartehnikat?", a: "Jah, vajadusel pakume välja sobivaid lahendusi ja soetame need tootjatelt. Võite ka ise osta ja meile paigaldamiseks anda." },
      { q: "Kas annate garantii hüdroisolatsioonile?", a: "Jah. Hüdroisolatsioonile anname garantii, mis on sageli pikem kui tavaliste viimistlustööde garantii." },
    ],
    related: ["torutood", "plaatimine", "siseviimistlus", "ehitusprahi"],
    icon: "shield",
  },
  {
    key: "ventilatsioon",
    slug: "remonditeenused-tallinnas/ventilatsioonide-ehitus-ja-hooldus",
    category: "Remonditeenused",
    categoryHref: "/remonditeenused-tallinnas",
    serviceName: "Ventilatsioonide ehitus ja hooldus",
    serviceType: "Ventilatsioonitööd",
    title: "Ventilatsioonide ehitus ja hooldus",
    accent: "äripindadel",
    heroImage: "/ventilatsioon-1.jpg",
    contentImage: "/ventilatsioon-2.webp",
    description: "Ventilatsioonisüsteemide ehitus, hooldus, remont ja väiksemad ümberehitused äripindadel ning tehnoruumides.",
    cta: "Küsi ventilatsioonitööde pakkumist",
    introTitle: "Ventilatsioon mõjutab nii mugavust kui töövõimet",
    introFirst: "Halb õhuvahetus muutub kiiresti kasutajate probleemiks.",
    introSecond: "SPS aitab süsteemi hooldada, parandada või ümber ehitada.",
    serviceTitle: "Mida sisaldavad ventilatsioonitööd?",
    groups: [["Ülevaatus", "Enne tööd tuleb aru saada süsteemi seisust.", ["Õhuvahetuse probleemid", "Seadmete seis", "Kanalite ja ligipääsu kontroll"]], ["Tööd", "Töö ulatus sõltub süsteemist ja eesmärgist.", ["Hooldus", "Remont", "Väiksemad ümberehitused", "Seadmete paigaldus"]], ["Järelkontroll", "Tulemus peab parandama ruumi kasutuskvaliteeti.", ["Toimivuse kontroll", "Hooldusgraafik", "Edasised soovitused"]]],
    strengths: [["Ärikinnisvara kogemus", "Ventilatsioonitööd peavad sobima hoone kasutusega.", "briefcase"], ["Hoolduslepingud", "Regulaarne hooldus aitab rikkeid ennetada.", "clock"], ["Tehniline tervik", "Ventilatsioon seostub tihti elektri ja viimistlusega.", "shield"], ["Kiire korraldus", "Rikete korral aitame tööde järjekorra paika saada.", "clipboard"]],
    processSteps: [["Probleemi kirjeldus", "Täpsustame sümptomid ja ruumi kasutuse."], ["Ülevaatus", "Hindame süsteemi ja ligipääsu."], ["Tööplaan", "Pakume sobiva lahenduse."], ["Teostus", "Teeme hoolduse, remondi või paigalduse."], ["Kontroll", "Anname soovitused edasiseks hoolduseks."]],
    pricingFactors: ["süsteemi tüüp ja suurus", "ligipääs seadmetele", "tööde ulatus", "materjalide ja varuosade vajadus", "tööde ajastus", "hoolduslepingu vajadus"],
    faqItems: [
      { q: "Kui sageli peaks ventilatsiooni puhastama?", a: "Sõltub keskkonnast. Kontorites tavaliselt 1-2 korda aastas, köökides ja tootmishoonetes oluliselt sagedamini. Filtreid vahetatakse 3-6 kuu tagant." },
      { q: "Millal on vaja ventilatsiooni tervet süsteemi renoveerida?", a: "Kui süsteem on üle 15-20 aasta vana, tekivad pidevalt rikked, energiakulu on suur või õhu kvaliteet ei vasta normidele. Meie audit ütleb täpselt, mida soovitame." },
      { q: "Kas saate teostada töid tööajal?", a: "Enamus hooldustöid saame teha tööajal ilma segajaid. Suuremate paigalduste puhul planeerime nädalavahetustele või tööpausidele." },
      { q: "Kas annate garantii ventilatsioonitöödele?", a: "Jah. Paigaldustöödele 2 aastat, seadmetele tootja garantii (sageli 5 aastat)." },
      { q: "Kas kaetud hooldusleping võib säästa raha?", a: "Jah, reeglina jah. Regulaarne hooldus väldib suuri hädaremontide kulusid ja hoiab energiakulu madalal. Tavaliselt tasub leping end ära juba esimese aastaga." },
    ],
    related: ["elektritood", "siseviimistlus", "remonditeenused", "kontor"],
    icon: "shield",
  },
  {
    key: "plaatimine",
    slug: "remonditeenused-tallinnas/plaatimistood",
    category: "Remonditeenused",
    categoryHref: "/remonditeenused-tallinnas",
    serviceName: "Plaatimistööd",
    serviceType: "Plaatimistööd",
    title: "Plaatimistööd",
    accent: "äripindadel",
    heroImage: "/plaatimistood-1.jpg",
    contentImage: "/plaatimistood-2.webp",
    description: "Plaatimistööd sanitaarruumides, köögialadel, ühiskasutatavates ruumides ja äripindadel koos aluspinna ettevalmistusega.",
    cta: "Küsi plaatimistööde pakkumist",
    introTitle: "Plaatimistöö kvaliteet paistab välja iga päev",
    introFirst: "Sirged vuugid ja õige aluspind määravad tulemuse kestvuse.",
    introSecond: "SPS planeerib plaatimistöö koos ettevalmistuse ja viimistlusega.",
    serviceTitle: "Mida sisaldavad plaatimistööd?",
    groups: [["Ettevalmistus", "Aluspind otsustab, kui kaua tulemus kestab.", ["Vana katte eemaldus", "Tasandus", "Hüdroisolatsioon vajadusel"]], ["Plaatimine", "Töö vajab täpsust ja materjalide sobivust.", ["Plaatide paigaldus", "Vuukimine", "Nurkade ja üleminekute lahendus"]], ["Lõppviimistlus", "Ruum peab jääma kasutusvalmis.", ["Silikoonimine", "Puhastus", "Üleandmine"]]],
    strengths: [["Täpsus", "Sirged vuugid ja üleminekud loovad professionaalse tulemuse.", "sparkle"], ["Niiskuskindlus", "Märgades ruumides on ettevalmistus kriitiline.", "shield"], ["Ajakava", "Plaatimist ei saa kiirustada valede kuivamisaegade arvelt.", "clock"], ["Korralik üleandmine", "Pind antakse üle puhta ja kontrollituna.", "clipboard"]],
    processSteps: [["Mõõdistus", "Hindame pinna ja materjali."], ["Ettevalmistus", "Teeme aluspinna valmis."], ["Paigaldus", "Paigaldame plaadid plaani järgi."], ["Vuukimine", "Viimistleme vuugid ja nurgad."], ["Üleandmine", "Kontrollime tulemuse ja koristame tööala."]],
    pricingFactors: ["pindala ja plaatide formaat", "aluspinna seisukord", "hüdroisolatsiooni vajadus", "lõigete ja detailide hulk", "materjalide valik", "tööde ajastus"],
    faqItems: [
      { q: "Kui kaua võtab keskmise WC-ruumi plaatimine?", a: "Väike WC-ruum (kuni 5m²) tavaliselt 3-5 tööpäeva koos hüdroisolatsiooniga ja kuivamisaegadega. Suuremate ruumide puhul proportsionaalselt kauem." },
      { q: "Kas teete ka vanade plaatide eemaldamist?", a: "Jah. Eemaldame vanad plaadid, ettevalmistame pinna, teeme uue hüdroisolatsiooni ja paigaldame uued plaadid. Kogu protsess ühest kohast." },
      { q: "Millised plaaditüübid teile sobivad?", a: "Kõik enamlevinud: keraamika, klaas, looduslik kivi, marmor, mosaiik." },
      { q: "Kas on vaja enne plaatimist lasta aluspind ette valmistada?", a: "Jah. Plaatimise aluspind peab olema tasane, kuiv ja kandev. Vajadusel teeme eelnevalt ka tasandustööd. Hindame olukorda objektile tulles." },
      { q: "Kas annate garantii plaatimistöödele?", a: "Jah. Plaatimistöödele 2 aastat garantii, hüdroisolatsioonile sama või pikem. Kirjalik leping ja selged tingimused." },
    ],
    related: ["sanitaar", "siseviimistlus", "ehitusprahi", "torutood"],
    icon: "floor",
  },
  {
    key: "katuseremont",
    slug: "remonditeenused-tallinnas/katuse-remont",
    category: "Remonditeenused",
    categoryHref: "/remonditeenused-tallinnas",
    serviceName: "Katuse remont",
    serviceType: "Katuse remont",
    title: "Katuse remont",
    accent: "ärikinnistutel",
    heroImage: "/katuseremont-1.jpg",
    contentImage: "/katuseremont2.webp",
    description: "Katuse lekete, läbiviikude, vihmaveesüsteemide ja väiksemate kahjustuste remont ärikinnistutel Tallinnas ning Harjumaal.",
    cta: "Küsi katuse remondi pakkumist",
    introTitle: "Katuse väike probleem võib kiiresti kalliks muutuda",
    introFirst: "Leke või katkine läbiviik vajab kiiret kontrolli.",
    introSecond: "SPS aitab katuse remondi siduda kinnistu hooldusega.",
    serviceTitle: "Mida sisaldab katuse remont?",
    groups: [["Diagnostika", "Kõigepealt tuleb tuvastada kahju põhjus.", ["Lekke asukoha otsing", "Läbiviikude kontroll", "Vihmaveesüsteemi ülevaatus"]], ["Remont", "Töö ulatus sõltub katuse tüübist.", ["Lokaalsed parandused", "Läbiviikude tihendamine", "Vihmaveesüsteemi parandused"]], ["Ennetus", "Regulaarne kontroll aitab kahju vältida.", ["Hooldussoovitused", "Perioodiline kontroll", "Talvise koormuse arvestus"]]],
    strengths: [["Kiire diagnostika", "Lekke puhul on oluline põhjus leida, mitte ainult jälg katta.", "clock"], ["Kinnistu tervik", "Katuse töö seostub sageli vihmavee ja fassaadiga.", "briefcase"], ["Ohutus", "Katuse töö vajab korralikku ligipääsu ja tööohutust.", "shield"], ["Hooldusmõtlemine", "Aitame vältida korduvaid probleeme.", "clipboard"]],
    processSteps: [["Probleemi kirjeldus", "Täpsustame lekke või kahjustuse."], ["Ülevaatus", "Hindame katuse seisukorda."], ["Lahendus", "Pakume remondi ulatuse."], ["Teostus", "Teeme kokkulepitud parandused."], ["Soovitus", "Anname edasise hoolduse soovituse."]],
    pricingFactors: ["kahjustuse ulatus", "katuse tüüp ja ligipääs", "materjalide vajadus", "tööohutuse nõuded", "kiireloomulisus", "kas lisandub vihmaveesüsteemi töö"],
    faqItems: [
      { q: "Kui sageli peaks katust kontrollima?", a: "Soovituslik on kevadel pärast talvekahjustusi ja sügisel enne talve. Lisaks peale tugevaid torme. Hoolduslepinguga kliendid saavad automaatselt regulaarset ülevaatust." },
      { q: "Kuidas leiate katuselekke allika?", a: "Katuselekke allikas ei ole tihti seal, kus vesi sisse tuleb, sest vesi võib joosta katuse all. Kasutame termokaameraid ja süsteemset lähenemist lekke tegeliku koha leidmiseks." },
      { q: "Kui kaua kestab lamekatuse renoveerimine?", a: "Kvaliteetne lamekatuse renoveerimine kestab 15-25 aastat, sõltuvalt materjalidest ja hooldusest. Regulaarne hooldus pikendab eluiga veelgi." },
      { q: "Kas tegelete ka talvise lumekoristusega katuselt?", a: "Jah. Suured lumekoormused võivad kahjustada katust ja isegi ohustada konstruktsiooni. Pakume talvist lumekoristust katuselt." },
      { q: "Kas annate garantii katusetöödele?", a: "Jah. Paigaldustöödele 2 aastat, materjalidele tootja garantii, sageli 10+ aastat. Suuremad renoveerimised tulevad pikema töögarantiiga." },
    ],
    related: ["fassaadipesu", "kojameheteenus2", "lumekoristus", "remonditeenused"],
    icon: "construction",
  },
  {
    key: "lammutus",
    slug: "remonditeenused-tallinnas/lammutustood",
    category: "Remonditeenused",
    categoryHref: "/remonditeenused-tallinnas",
    serviceName: "Lammutustööd",
    serviceType: "Lammutustööd",
    title: "Lammutustööd",
    accent: "remondi ettevalmistuseks",
    heroImage: "/lammutustood-1.jpg",
    contentImage: "/lammutustood-2.webp",
    description: "Väiksemad lammutustööd, demontaaž, ruumide tühjendamine ja prahi äravedu enne remonti või ümberehitust.",
    cta: "Küsi lammutustööde pakkumist",
    introTitle: "Korralik lammutus teeb remondi lihtsamaks",
    introFirst: "Kiire lõhkumine ilma plaanita tekitab lisariske.",
    introSecond: "SPS seob lammutuse prahi äraveo ja järelkoristusega.",
    serviceTitle: "Mida sisaldavad lammutustööd?",
    groups: [["Ettevalmistus", "Selgitame, mida eemaldada ja mida kaitsta.", ["Tööala piiritlemine", "Kaitsetööd", "Jäätmete hindamine"]], ["Lammutus", "Töö tehakse kontrollitult ja ruumi arvestades.", ["Vaheseinte eemaldus", "Põranda- ja seinakatete eemaldus", "Inventari demontaaž"]], ["Jäätmed ja koristus", "Objekt peab jääma järgmiseks etapiks valmis.", ["Sorteerimine", "Ehitusprahi äravedu", "Järelkoristus"]]],
    strengths: [["Kontrollitud protsess", "Lammutus ei tohi kahjustada alles jäävaid konstruktsioone.", "shield"], ["Prahi äravedu", "Jäätmekäitlus on osa töö planeerimisest.", "construction"], ["Remondiga seotud", "Järgmine etapp saab alata kiiremini.", "briefcase"], ["Puhas üleandmine", "Tööala antakse üle korrastatult.", "sparkle"]],
    processSteps: [["Ülevaatus", "Täpsustame eemaldatavad osad."], ["Kaitse", "Kaitseme alles jäävad pinnad."], ["Lammutus", "Teeme töö kontrollitult."], ["Äravedu", "Korraldame jäätmed ja transpordi."], ["Üleandmine", "Jätame pinna järgmiseks tööks valmis."]],
    pricingFactors: ["lammutuse maht", "materjalide ja jäätmete tüüp", "korrus ja ligipääs", "kaitsetööde vajadus", "prahi äravedu", "tööde ajastus"],
    faqItems: [
      { q: "Kui kiiresti saab alustada lammutustöödega?", a: "Tavaliselt 3-7 tööpäeva pärast pakkumise kinnitamist ja lepingu sõlmimist. Kiireloomuliste projektide puhul võimalik ka kiiremini." },
      { q: "Kas tegelete ka jäätmete äraveoga?", a: "Jah, see on meie lammutustööde loomulik osa. Sorteerime kohapeal, korraldame transporti ja haldame dokumentatsiooni." },
      { q: "Kuidas kaitsete ümberkaudseid ruume lammutustolmu eest?", a: "Kasutame tolmukatteid, tihendame uste avad, niisutame lammutatavaid pindu ja kasutame tolmuimejaid. Suuremate tööde puhul kasutame ka õhupuhasteid." },
      { q: "Kas saate lammutada ainult osa ruumist?", a: "Jah. Enamik meie lammutustöid on tegelikult osaline demontaaž, näiteks vaheseinte eemaldamine või sanitaarruumi sisemuse lammutus. Hindame täpselt, mis tuleb eemaldada." },
      { q: "Kas saate käsitseda ka ohtlikke jäätmeid nagu asbest?", a: "Asbestitöö on spetsialiseeritud valdkond, millele on vajalik eriluba. Kui leiame asbesti olemasolevast konstruktsioonist, koordineerime vastava sertifikaadiga partneriga." },
    ],
    related: ["ehitusprahi", "ehitusjargne", "siseviimistlus", "sanitaar"],
    icon: "construction",
  },
  {
    key: "kojameheteenus2",
    slug: "remonditeenused-tallinnas/kojameheteenus",
    category: "Remonditeenused",
    categoryHref: "/remonditeenused-tallinnas",
    serviceName: "Kojamehe teenus",
    serviceType: "Kinnistu hooldus",
    title: "Kojamehe teenus",
    accent: "aastaringselt",
    heroImage: "/kojameheteenus-1.jpg",
    contentImage: "/kojameheteenus_2.jpg",
    description: "Aastaringne kojamehe teenus, välialade korrashoid, libedusetõrje, lehtede koristus ja kinnistu igapäevane hooldus.",
    cta: "Küsi kojamehe teenuse pakkumist",
    introTitle: "Kinnistu korrashoid peab olema järjepidev",
    introFirst: "Väliala probleemid mõjutavad külastaja esimest muljet.",
    introSecond: "SPS seob kojamehe töö hooajaliste hooldustega.",
    serviceTitle: "Mida sisaldab kojamehe teenus?",
    groups: [["Igapäevane hooldus", "Kinnistu välimus vajab regulaarset tähelepanu.", ["Sissepääsude korrashoid", "Prügi ja lahtise mustuse eemaldus", "Väiksemad korrastustööd"]], ["Hooajatööd", "Tööde rõhk muutub aastaajaga.", ["Libedusetõrje", "Lehtede koristus", "Lumetööde koordineerimine"]], ["Kontroll", "Probleemid tuleb märgata enne kaebust.", ["Objekti ülevaatus", "Puuduste märkamine", "Tööde raporteerimine"]]],
    strengths: [["Aastaringne teenus", "Hooldus ei sõltu ainult ühest hooajast.", "clock"], ["Üks partner", "Välikoristus, lumi ja lehed saab siduda.", "briefcase"], ["Regulaarne kontroll", "Objektijuht aitab kvaliteeti hoida.", "clipboard"], ["Esinduslik väliala", "Korrashoid algab hoone ümbrusest.", "sparkle"]],
    processSteps: [["Objekti ülevaatus", "Kaardistame väliala ja sissepääsud."], ["Graafik", "Lepime kokku sageduse ja hooajatööd."], ["Teostus", "Hooldame kinnistut kokkulepitud rütmis."], ["Lisatööd", "Korraldame vajadusel lehed, lumi või pesu."], ["Kontroll", "Anname tagasisidet probleemidest."]],
    pricingFactors: ["kinnistu suurus", "sissepääsude ja kõnniteede hulk", "hooldussagedus", "hooajaliste tööde ulatus", "libedusetõrje vajadus", "lisateenused"],
    faqItems: [
      { q: "Mida kõike kojamehe teenus hõlmab?", a: "Kojamehe teenus võib hõlmata territooriumi koristust, prügikastide tühjendust, muru niitmist, lehtede koristust, lumekoristust ja väiksemaid remonditöid. Sõltuvalt teie vajadustest koostame sobiva teenusepaketi." },
      { q: "Kui tihti kojamees teie objektil käib?", a: "Sagedus sõltub kokkuleppest — alates ühest korrast nädalas kuni iga päev. Enamikul klientidest on regulaarne kord nädalas või kaks korda nädalas." },
      { q: "Kas kojamees tegeleb ka lumekoristusega talvel?", a: "Jah. Kojamehe teenus hõlmab tavaliselt ka talvist hooldust: lumekoristus, liivakastide täitmine ja libeduse tõrje. See on loomulik osa aastaringist tööst." },
      { q: "Kas kojamees saab teha väiksemaid remonditöid?", a: "Jah, kojamees tegeleb igapäevaste väiksemate remonditöödega nagu uste reguleerimine, lukkude vahetus, lambipirnide vahetus, riiulite paigaldus jms. Suuremad remonditööd koordineerime meie meeskonnaga." },
      { q: "Kas kojamehe teenusega kaasneb kindlustus?", a: "Jah, kõik SPS Grupi töötajad on kindlustatud. Teie objektile ja varale tekitatud kahju hüvitatakse." },
    ],
    related: ["lumekoristus", "lehed2", "muru2", "tanavakividePesu"],
    icon: "leaf",
  },
  {
    key: "lehed2",
    slug: "remonditeenused-tallinnas/lehtedekoristamine",
    category: "Remonditeenused",
    categoryHref: "/remonditeenused-tallinnas",
    serviceName: "Lehtede koristus",
    serviceType: "Lehtede koristamine",
    title: "Lehtede koristus",
    accent: "kinnistutel",
    heroImage: "/lehekoristus-1.jpg",
    contentImage: "/lehekoristus-2.jpg",
    description: "Lehtede koristamine, kokku kogumine ja äravedu kinnistutelt, parklatest, kõnniteedelt ja haljasaladelt.",
    cta: "Küsi lehtede koristuse pakkumist",
    introTitle: "Sügisene lehemass muutub kiiresti ohuks ja mustuseks",
    introFirst: "Märjad lehed teevad kõnniteed libedaks.",
    introSecond: "SPS planeerib lehekoristuse kinnistu kasutuse järgi.",
    serviceTitle: "Mida sisaldab lehtede koristus?",
    groups: [["Koristus", "Eemaldame lehed kohtadest, kus need segavad kasutust.", ["Kõnniteed", "Parklad", "Sissepääsud", "Haljasalad"]], ["Kogumine", "Lehed tuleb kokku koguda ja käsitleda.", ["Puhuritööd", "Riisumine", "Kottidesse või konteinerisse kogumine"]], ["Äravedu", "Vajadusel viiakse lehed objektist ära.", ["Lehtede äravedu", "Järelpuhastus", "Korduv graafik sügisel"]]],
    strengths: [["Kiire hooajatöö", "Lehekoristus vajab reageerimist ilmastiku järgi.", "clock"], ["Ohutu ligipääs", "Hoiame sissepääsud ja kõnniteed kasutatavad.", "shield"], ["Väliala tervik", "Teenust saab siduda kojamehe ja lumetöödega.", "leaf"], ["Äravedu", "Lehed ei jää kinnistule hunnikutesse seisma.", "construction"]],
    processSteps: [["Kinnistu ülevaatus", "Täpsustame alad ja lehemassi."], ["Graafik", "Lepime kokku ühekordse või korduva koristuse."], ["Koristus", "Kogume lehed kokku."], ["Äravedu", "Vajadusel viime lehed ära."], ["Järelkontroll", "Kontrollime sissepääsud ja käiguteed."]],
    pricingFactors: ["koristatava ala suurus", "lehtede kogus", "äraveo vajadus", "ligipääs tehnikale", "koristuse sagedus", "ilmastiku ja ajastuse mõju"],
    faqItems: [
      { q: "Millal on parim aeg lehtede koristuseks?", a: "Sügisel, kui lehed on langenud, on põhiline koristusaeg. Kuid pakume lehtede koristust ka kevadel ja suvel vastavalt vajadusele. Regulaarne koristus hoiab ala korras kogu aasta vältel." },
      { q: "Kas te koristate ka suuri territooriume?", a: "Jah. Oleme harjunud töötama nii väikeste ärihoone õuealade kui ka suurte territooriumitega. Vajadusel toome kohale suurema tehnika ja meeskonna." },
      { q: "Mida teete kogutud lehtedega?", a: "Kogume lehed kokku, laadime veokisse ja viime nõuetekohaselt käitlusesse. Pakume ka kompostimist, kui see on teie sooviks." },
      { q: "Kas koristate ka vihmase ilmaga?", a: "Märjad lehed on raskemad ja võivad tekitada libedust. Kui vihm pole väga tugev, teostame koristuse siiski. Tugeva vihma korral lepime kokku uue aja." },
      { q: "Kas teenus hõlmab ka jäätmete äravedu?", a: "Jah, alati. Kogutud lehed ja haljastusjäätmed viime oma transpordiga ära ja käitleme vastavalt nõuetele." },
    ],
    related: ["kojameheteenus2", "muru2", "lumekoristus", "valikoristus"],
    icon: "leaf",
  },
  {
    key: "muru2",
    slug: "remonditeenused-tallinnas/muruniitmine",
    category: "Remonditeenused",
    categoryHref: "/remonditeenused-tallinnas",
    serviceName: "Muru niitmine",
    serviceType: "Muruniitmine",
    title: "Muru niitmine",
    accent: "kinnistutel",
    heroImage: "/muruniitmine-1.jpg",
    contentImage: "/muruniitmin-2.jpg",
    description: "Regulaarne muruniitmine, servade trimmerdamine ja haljasalade hooldus ärikinnistutel ning korteriühistutel.",
    cta: "Küsi muruniitmise pakkumist",
    introTitle: "Hooldatud muru loob korras kinnistu tunde",
    introFirst: "Kõrge muru ja niitmata servad rikuvad üldmulje kiiresti.",
    introSecond: "SPS koostab niitmisgraafiku hooaja ja kasvukiiruse järgi.",
    serviceTitle: "Mida sisaldab muru niitmine?",
    groups: [["Niitmine", "Graafik sõltub kasvust ja objekti ootustest.", ["Regulaarne niitmine", "Suuremate pindade hooldus", "Sissepääsude ümbrus"]], ["Viimistlus", "Servad otsustavad, kas ala näeb hooldatud välja.", ["Trimmerdamine", "Teede puhastus", "Takistuste ümbrus"]], ["Hooajahooldus", "Haljasala vajab eri ajal eri töid.", ["Niite kogumine vajadusel", "Lehtede koristus", "Kojamehe teenusega sidumine"]]],
    strengths: [["Hooajaline graafik", "Sagedust saab muuta vastavalt kasvule.", "clock"], ["Viimistletud servad", "Trimmerdamine annab puhta lõpptulemuse.", "sparkle"], ["Sobib suurtele pindadele", "Töö planeeritakse tehnika ja ligipääsu järgi.", "briefcase"], ["Üks partner", "Muru, lehed ja lumi saab siduda kinnistu hoolduseks.", "leaf"]],
    processSteps: [["Ala ülevaatus", "Hindame niidetava ala ja takistused."], ["Sagedus", "Lepime kokku hooajalise graafiku."], ["Niitmine", "Teeme töö kokkulepitud ajal."], ["Servad", "Trimmerdame vajalikud kohad."], ["Järelpuhastus", "Puhastame käiguteed niitejääkidest."]],
    pricingFactors: ["niitmisala pindala", "niitmise sagedus", "servade ja takistuste hulk", "niite kogumise vajadus", "ligipääs tehnikale", "hooajalepingu pikkus"],
    faqItems: [
      { q: "Kui sageli peaks muru niitma?", a: "Sõltub aastaajast ja muru kasvukiirusest. Suvekuudel tavaliselt kord nädalas, kevadel ja sügisel vastavalt vajadusele. Regulaarne niitmine hoiab muru tervena ja korralikuna." },
      { q: "Kas tegelete ka muru ääriste ja trimmerdamisega?", a: "Jah. Muru niitmine hõlmab alati ka ääriste trimmerdamist ja servade korrastamist. Teeme töö lõpuni — kõik kohad saavad korralikult niidetud." },
      { q: "Mis juhtub niidetud rohuga?", a: "Pakume nii niidetud rohu kogumist kui ka jätmist. Kogumise puhul korjame muru kokku ja viime minema. Jätmise korral jääb peenestatud muru murule väetiseks." },
      { q: "Kas niidate ka vihmase ilmaga?", a: "Vältime niitmist tugeva vihma ajal, sest märg muru jääb ebaühtlane ja niiduk võib libiseda. Leppime kokku sobiva aja, kui ilm paraneb." },
      { q: "Kui suuri pindasid te niidate?", a: "Niidame nii väikeseid kontorihoone murukaardikuid kui ka suuri territooriume. Meil on erineva suurusega niidukid, et valida igale pinnale sobiv tehnika." },
    ],
    related: ["lehed2", "kojameheteenus2", "valikoristus", "tanavakividePesu"],
    icon: "leaf",
  },
];

export const extendedServicePages = Object.fromEntries(extraServiceConfigs.map((config) => [config.key, makeData(config)])) as Record<string, ServiceSeoData>;

const existingLinks = Object.values(serviceSeoPages).map((page) => ({
  title: page.serviceName,
  href: `/koristusteenus/${page.slug}`,
}));

const extraLinks = Object.values(extendedServicePages).map((page) => ({
  title: page.serviceName,
  href: `/${page.slug}`,
}));

const allLabLinks = [...existingLinks, ...extraLinks];

function relatedService(key: string): ServiceSeoData["relatedServices"][number] {
  const page = extendedServicePages[key] ?? serviceSeoPages[key];
  if (!page) {
    return {
      title: "Puhastusteenused",
      href: "/puhastusteenused",
      text: "SPS Grupi eripuhastusteenused äripindadele.",
      icon: "sparkle",
    };
  }

  const config = extraServiceConfigs.find((item) => item.key === key);
  const existingIcons: Record<string, SeoIcon> = {
    kontor: "briefcase",
    kaubandus: "store",
    tootmishooned: "factory",
    koolid: "school",
    akendePesu: "window",
    fassaadipesu: "construction",
    lumekoristus: "clock",
    valikoristus: "sparkle",
    tanavakividePesu: "floor",
  };

  return {
    title: page.serviceName,
    href: key in extendedServicePages ? `/${page.slug}` : `/koristusteenus/${page.slug}`,
    text: page.metadata.description,
    icon: config?.icon ?? existingIcons[key] ?? "briefcase",
  };
}

Object.values(extendedServicePages).forEach((page) => {
  page.serviceLinks = allLabLinks;
});

extraServiceConfigs.forEach((config) => {
  extendedServicePages[config.key].relatedServices = config.related.map(relatedService);
});
