import type { ReactNode } from 'react'
import type { Locale } from '@/lib/slug-map'
import { MuruniitminePageView } from '@/app/_pages/koristusteenus/valikoristus/muruniitmine/page'
import { KojameheteenusPageView } from '@/app/_pages/koristusteenus/valikoristus/kojameheteenus/page'
import { LehtedekoristaminePageView } from '@/app/_pages/koristusteenus/valikoristus/lehtedekoristamine/page'
import { LumekoristusPageView } from '@/app/_pages/koristusteenus/valikoristus/lumekoristus/page'
import { AkendePesuPageView } from '@/app/_pages/koristusteenus/valikoristus/akende-pesu/page'
import { FassaadipesuPageView } from '@/app/_pages/koristusteenus/valikoristus/fassaadipesu/page'
import { TanavakividePesuPageView } from '@/app/_pages/koristusteenus/valikoristus/tanavakivide-pesu-ja-hooldus/page'
import { GrafitiEemaldaminePageView } from '@/app/_pages/koristusteenus/valikoristus/grafiti-eemaldamine/page'
import { EhitusprahiPageView } from '@/app/_pages/ehitusprahi-aravedu/page'
import { PuhastusteenusedPageView } from '@/app/_pages/puhastusteenused/page'
import { RemonditeenusedPageView } from '@/app/_pages/remonditeenused-tallinnas/page'
import { VaipadePuhastusPageView } from '@/app/_pages/puhastusteenused/vaipade-puhastus/page'
import { SuurpuhastusPageView } from '@/app/_pages/puhastusteenused/suurpuhastus/page'
import { EhitusjargneKoristusPageView } from '@/app/_pages/puhastusteenused/ehitusjargne-koristus/page'
import { EskalaatoriteSuvapuhastusPageView } from '@/app/_pages/puhastusteenused/eskalaatorite-suvapuhastus/page'
import { DesinfitseeriminePageView } from '@/app/_pages/puhastusteenused/desinfitseerimine/page'
import { PorandateHooldusPageView } from '@/app/_pages/puhastusteenused/porandate-hooldus/page'
import { SuitsuJaTulekahjustustePuhastaminePageView } from '@/app/_pages/puhastusteenused/suitsu-ja-tulekahjustuste-puhastamine/page'
import { ElektritoodPageView } from '@/app/_pages/remonditeenused-tallinnas/elektritood/page'
import { TorutoodPageView } from '@/app/_pages/remonditeenused-tallinnas/torutood/page'
import { SiseviimistlustoodPageView } from '@/app/_pages/remonditeenused-tallinnas/siseviimistlustood/page'
import { SanitaarremontPageView } from '@/app/_pages/remonditeenused-tallinnas/sanitaarremont-ja-umberehitus/page'
import { VentilatsioonidPageView } from '@/app/_pages/remonditeenused-tallinnas/ventilatsioonide-ehitus-ja-hooldus/page'
import { PlaatinistoodPageView } from '@/app/_pages/remonditeenused-tallinnas/plaatimistood/page'
import { KatuseRemontPageView } from '@/app/_pages/remonditeenused-tallinnas/katuse-remont/page'
import { LammutustoodPageView } from '@/app/_pages/remonditeenused-tallinnas/lammutustood/page'
import { ValikoristusPageView } from '@/app/_pages/koristusteenus/valikoristus/page'
import { KontaktPageView } from '@/app/_pages/kontakt/page'
import { SpsGruppPageView } from '@/app/_pages/sps-grupp/page'
import { KontoriKoristusPageView } from '@/app/_pages/koristusteenus/kontori-koristus/page'
import { HoolduskoristusPageView } from '@/app/_pages/koristusteenus/hoolduskoristus/page'
import { KaubanduspindadeKoristusPageView } from '@/app/_pages/koristusteenus/kaubanduspindade-koristus/page'
import { TootmishooneteKoristusPageView } from '@/app/_pages/koristusteenus/tootmishoonete-koristus/page'
import { KoolideKoristaminePageView } from '@/app/_pages/koristusteenus/koolide-koristamine/page'
import { KoristusteenusPageView } from '@/app/_pages/koristusteenus/page'
import { TuleMeileToolePageView } from '@/app/_pages/tule-meile-toole/page'

export type LocalizedPageRenderer = (locale: Locale) => ReactNode

export const localizedPageRegistry: Record<string, LocalizedPageRenderer> = {
  '/koristusteenus/valikoristus/muruniitmine': (locale) => <MuruniitminePageView locale={locale} />,
  '/koristusteenus/valikoristus/kojameheteenus': (locale) => <KojameheteenusPageView locale={locale} />,
  '/koristusteenus/valikoristus/lehtedekoristamine': (locale) => <LehtedekoristaminePageView locale={locale} />,
  '/koristusteenus/valikoristus/lumekoristus': (locale) => <LumekoristusPageView locale={locale} />,
  '/koristusteenus/valikoristus/akende-pesu': (locale) => <AkendePesuPageView locale={locale} />,
  '/koristusteenus/valikoristus/fassaadipesu': (locale) => <FassaadipesuPageView locale={locale} />,
  '/koristusteenus/valikoristus/tanavakivide-pesu-ja-hooldus': (locale) => <TanavakividePesuPageView locale={locale} />,
  '/koristusteenus/valikoristus/grafiti-eemaldamine': (locale) => <GrafitiEemaldaminePageView locale={locale} />,
  '/ehitusprahi-aravedu': (locale) => <EhitusprahiPageView locale={locale} />,
  '/puhastusteenused': (locale) => <PuhastusteenusedPageView locale={locale} />,
  '/remonditeenused-tallinnas': (locale) => <RemonditeenusedPageView locale={locale} />,
  '/puhastusteenused/vaipade-puhastus': (locale) => <VaipadePuhastusPageView locale={locale} />,
  '/puhastusteenused/suurpuhastus': (locale) => <SuurpuhastusPageView locale={locale} />,
  '/puhastusteenused/ehitusjargne-koristus': (locale) => <EhitusjargneKoristusPageView locale={locale} />,
  '/puhastusteenused/eskalaatorite-suvapuhastus': (locale) => <EskalaatoriteSuvapuhastusPageView locale={locale} />,
  '/puhastusteenused/koroonaviiruse-jargne-puhastus': (locale) => <DesinfitseeriminePageView locale={locale} />,
  '/puhastusteenused/porandate-hooldus': (locale) => <PorandateHooldusPageView locale={locale} />,
  '/puhastusteenused/suitsu-ja-tulekahjustuste-puhastamine': (locale) => <SuitsuJaTulekahjustustePuhastaminePageView locale={locale} />,
  '/remonditeenused-tallinnas/elektritood': (locale) => <ElektritoodPageView locale={locale} />,
  '/remonditeenused-tallinnas/torutood': (locale) => <TorutoodPageView locale={locale} />,
  '/remonditeenused-tallinnas/siseviimistlustood': (locale) => <SiseviimistlustoodPageView locale={locale} />,
  '/remonditeenused-tallinnas/sanitaarremont-ja-umberehitus': (locale) => <SanitaarremontPageView locale={locale} />,
  '/remonditeenused-tallinnas/ventilatsioonide-ehitus-ja-hooldus': (locale) => <VentilatsioonidPageView locale={locale} />,
  '/remonditeenused-tallinnas/plaatimistood': (locale) => <PlaatinistoodPageView locale={locale} />,
  '/remonditeenused-tallinnas/katuse-remont': (locale) => <KatuseRemontPageView locale={locale} />,
  '/remonditeenused-tallinnas/lammutustood': (locale) => <LammutustoodPageView locale={locale} />,
  '/koristusteenus/valikoristus': (locale) => <ValikoristusPageView locale={locale} />,
  '/kontakt': (locale) => <KontaktPageView locale={locale} />,
  '/sps-grupp': (locale) => <SpsGruppPageView locale={locale} />,
  '/koristusteenus/kontori-koristus': (locale) => <KontoriKoristusPageView locale={locale} />,
  '/koristusteenus/hoolduskoristus': (locale) => <HoolduskoristusPageView locale={locale} />,
  '/koristusteenus/kaubanduspindade-koristus': (locale) => <KaubanduspindadeKoristusPageView locale={locale} />,
  '/koristusteenus/tootmishoonete-koristus': (locale) => <TootmishooneteKoristusPageView locale={locale} />,
  '/koolide-koristamine': (locale) => <KoolideKoristaminePageView locale={locale} />,
  '/koristusteenus': (locale) => <KoristusteenusPageView locale={locale} />,
  '/tule-meile-toole': (locale) => <TuleMeileToolePageView locale={locale} />,
}
